const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
let paperType = 'lined', currentPage = 0, currentNotebook = 0;
const notebookStorage = 'caderno-digital-notebooks';
let notebooks;
try { notebooks = JSON.parse(localStorage.getItem(notebookStorage)); } catch { notebooks = null; }
if (!Array.isArray(notebooks) || !notebooks.length) notebooks = [{ title: 'Meu caderno', cover: 'coral', paperType: 'lined', pages: [{ title: 'Página 1', content: $('#paperContent').innerHTML, stickers: [] }] }];
const stickerData = [
  ['📚','Livros','escola'],['✏️','Lápis','escola'],['🧠','Ideias','escola'],['💻','Computador','escola'],['🖥️','Monitor','escola'],['🔬','Ciência','escola'],['📐','Geometria','escola'],['🎓','Formatura','escola'],
  ['🌈','Arco-íris','diversao'],['🦄','Unicórnio','diversao'],['🎧','Música','diversao'],['⭐','Estrela','diversao'],['🎮','Game','diversao'],['🛼','Patins','diversao'],['🍓','Morango','natureza'],['🌻','Flor','natureza'],['🪴','Planta','natureza'],['🦋','Borboleta','natureza']
];

function activeNotebook() { return notebooks[currentNotebook]; }
function persistNotebooks() { try { localStorage.setItem(notebookStorage, JSON.stringify(notebooks)); } catch {} }
function saveCurrent() { const page=activeNotebook().pages[currentPage]; page.content = $('#paperContent').innerHTML; page.stickers = $$('.placed-sticker').map(el => ({emoji:el.textContent,x:el.style.left,y:el.style.top})); persistNotebooks(); }
function renderNotebooks() { $('#notebookList').innerHTML = notebooks.map((n,i)=>`<button class="${i===currentNotebook?'active':''}" data-notebook="${i}"><span class="notebook-dot ${n.cover}"></span>${n.title}</button>`).join(''); $$('#notebookList button').forEach(b=>b.onclick=()=>loadNotebook(+b.dataset.notebook)); }
function renderPages() { $('#pageList').innerHTML = activeNotebook().pages.map((p,i)=>`<button class="${i===currentPage?'active':''}" data-page="${i}">▤ ${p.title}</button>`).join(''); $$('#pageList button').forEach(b=>b.onclick=()=>loadPage(+b.dataset.page)); }
function loadPage(i, save=true) { if(save) saveCurrent(); currentPage=i; const p=activeNotebook().pages[i]; $('#paperContent').innerHTML=p.content; $('#stickerLayer').innerHTML=''; p.stickers.forEach(s=>placeSticker(s.emoji,s.x,s.y)); renderPages(); }
function loadNotebook(i) { saveCurrent(); currentNotebook=i; currentPage=0; const n=activeNotebook(); paperType=n.paperType; $('#notebook').className='notebook '+n.cover+'-cover'; $('#paper').className='paper '+paperType+'-paper'; $$('.cover-choice').forEach(b=>b.classList.toggle('selected',b.dataset.cover===n.cover)); $$('.paper-option').forEach(b=>b.classList.toggle('selected',b.dataset.paper===paperType)); $('#notebookTitle').textContent=n.title; renderNotebooks(); loadPage(0,false); }
let printNotebookIndex = 0, printPageIndex = 0;
function updatePrintPreview() { const notebook=notebooks[printNotebookIndex], page=notebook.pages[printPageIndex]; const paper=$('#printPaper'); paper.className='paper '+notebook.paperType+'-paper'; paper.innerHTML=`<div class="paper-content">${page.content}</div><div class="sticker-layer">${page.stickers.map(s=>`<span class="placed-sticker" style="left:${s.x};top:${s.y}">${s.emoji}</span>`).join('')}</div>`; }
function renderPrintOptions() { const notebookSelect=$('#printNotebookSelect'), pageSelect=$('#printPageSelect'); if (!notebookSelect || !pageSelect) return; if(printNotebookIndex>=notebooks.length) printNotebookIndex=0; notebookSelect.innerHTML=notebooks.map((n,i)=>`<option value="${i}">${n.title}</option>`).join(''); notebookSelect.value=printNotebookIndex; const notebook=notebooks[printNotebookIndex]; if(printPageIndex>=notebook.pages.length) printPageIndex=0; pageSelect.innerHTML=notebook.pages.map((p,i)=>`<option value="${i}">${p.title}</option>`).join(''); pageSelect.value=printPageIndex; updatePrintPreview(); }
function placeSticker(emoji, x='42%', y='42%') { const el=document.createElement('span'); el.className='placed-sticker'; el.textContent=emoji; el.style.left=x; el.style.top=y; el.setAttribute('aria-label','Adesivo '+emoji); enableDrag(el); $('#stickerLayer').append(el); }
function enableDrag(el) { let sx,sy,ox,oy; el.addEventListener('pointerdown',e=>{e.preventDefault();el.setPointerCapture(e.pointerId);sx=e.clientX;sy=e.clientY;ox=el.offsetLeft;oy=el.offsetTop;el.style.cursor='grabbing';}); el.addEventListener('pointermove',e=>{if(!el.hasPointerCapture(e.pointerId))return;const layer=$('#stickerLayer'), maxX=layer.clientWidth-el.offsetWidth, maxY=layer.clientHeight-el.offsetHeight;el.style.left=Math.max(0,Math.min(maxX,ox+e.clientX-sx))+'px';el.style.top=Math.max(0,Math.min(maxY,oy+e.clientY-sy))+'px';}); el.addEventListener('pointerup',e=>{el.releasePointerCapture(e.pointerId);el.style.cursor='grab';saveCurrent();}); el.addEventListener('dblclick',()=>{el.remove();saveCurrent();}); }

$$('.nav-item').forEach(button=>button.addEventListener('click',()=>{saveCurrent(); $$('.nav-item').forEach(b=>b.classList.toggle('active',b===button)); $$('.tab-panel').forEach(p=>p.classList.toggle('active',p.id===button.dataset.tab)); if(button.dataset.tab==='imprimir') renderPrintOptions(); $('.sidebar').classList.remove('open'); window.scrollTo({top:0,behavior:'smooth'}); }));
$('#printNotebookSelect').onchange=e=>{printNotebookIndex=+e.target.value;printPageIndex=0;renderPrintOptions();};
$('#printPageSelect').onchange=e=>{printPageIndex=+e.target.value;updatePrintPreview();};
$('#printButton').onclick=()=>window.print();
$('#menuButton').onclick=()=>$('.sidebar').classList.toggle('open');
$$('.cover-choice').forEach(b=>b.onclick=()=>{ $$('.cover-choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');activeNotebook().cover=b.dataset.cover;$('#notebook').className='notebook '+b.dataset.cover+'-cover'; persistNotebooks(); renderNotebooks(); });
$$('.paper-option').forEach(b=>b.onclick=()=>{paperType=b.dataset.paper;activeNotebook().paperType=paperType;$$('.paper-option').forEach(x=>x.classList.toggle('selected',x===b));$('#paper').className='paper '+paperType+'-paper';persistNotebooks();});
$('#newPage').onclick=()=>{saveCurrent();const pages=activeNotebook().pages;pages.push({title:'Página '+(pages.length+1),content:'<p class="date">NOVA PÁGINA</p><h2>Minha nova ideia ✦</h2><p>Comece a escrever aqui...</p>',stickers:[]});loadPage(pages.length-1);};
$('#newNotebook').onclick=()=>{const title=prompt('Qual é o nome do novo caderno?', 'Novo caderno');if(!title?.trim())return;saveCurrent();notebooks.push({title:title.trim(),cover:'lilac',paperType:'lined',pages:[{title:'Página 1',content:'<p class="date">NOVO CADERNO</p><h2>'+title.trim()+' ✦</h2><p>Comece a escrever aqui...</p>',stickers:[]}]});loadNotebook(notebooks.length-1);};
const initialNotebook = activeNotebook();
paperType = initialNotebook.paperType;
$('#notebook').className='notebook '+initialNotebook.cover+'-cover';
$('#paper').className='paper '+paperType+'-paper';
$('#notebookTitle').textContent=initialNotebook.title;
$$('.cover-choice').forEach(b=>b.classList.toggle('selected',b.dataset.cover===initialNotebook.cover));
$$('.paper-option').forEach(b=>b.classList.toggle('selected',b.dataset.paper===paperType));
renderNotebooks(); loadPage(0,false);

function renderStickers(category='todos'){const list=category==='todos'?stickerData:stickerData.filter(s=>s[2]===category);$('#stickerGallery').innerHTML=list.map(([emoji,name])=>`<button class="sticker-card" data-emoji="${emoji}"><span class="emoji">${emoji}</span><small>${name}</small></button>`).join('');$$('.sticker-card').forEach(b=>b.onclick=()=>{placeSticker(b.dataset.emoji);saveCurrent();});}renderStickers();
$$('.sticker-filter').forEach(b=>b.onclick=()=>{$$('.sticker-filter').forEach(x=>x.classList.toggle('active',x===b));renderStickers(b.dataset.category);});

const answers = {fotossíntese:'A fotossíntese é como a cozinha das plantas: usando luz do sol, água e gás carbônico, ela produz açúcar para ter energia e libera oxigênio. Acontece principalmente nas folhas, graças à clorofila.',equação:'Para resolver uma equação de 1º grau, deixe o x sozinho em um lado do sinal de igual. Exemplo: 2x + 4 = 10. Tire 4 dos dois lados: 2x = 6. Depois divida ambos por 2: x = 3.',resumo:'Para criar um bom resumo: 1) leia o assunto, 2) anote só as ideias principais com suas palavras, 3) use títulos e exemplos, e 4) releia tentando explicar sem olhar. Posso ajudar se você colar o texto aqui.',alura:'Nas aulas da Alura, pause quando surgir um conceito novo, anote a ideia principal e teste o que foi mostrado. Se você me disser o tema ou colar um trecho da aula, eu explico passo a passo com exemplos.'};
function reply(question){const q=question.toLowerCase();if(q.includes('fotossíntese'))return answers.fotossíntese;if(q.includes('equação')||q.includes('primeiro grau'))return answers.equação;if(q.includes('resumo'))return answers.resumo;if(q.includes('alura'))return answers.alura;return 'Ótima pergunta! Para estudar esse assunto, comece identificando os conceitos principais e procurando um exemplo prático. Conte qual parte está mais difícil ou cole um trecho do material que eu explico de um jeito mais simples.';}
function addMessage(text,type){const m=document.createElement('div');m.className='message '+type;m.textContent=text;$('#chatBox').append(m);$('#chatBox').scrollTop=$('#chatBox').scrollHeight;}
$('#aiForm').onsubmit=e=>{e.preventDefault();const input=$('#aiQuestion'),q=input.value.trim();if(!q)return;addMessage(q,'user');input.value='';setTimeout(()=>addMessage(reply(q),'luma'),250);};$$('.suggestions button').forEach(b=>b.onclick=()=>{$('#aiQuestion').value=b.dataset.question;$('#aiForm').requestSubmit();});

let recorder, chunks=[], recordTimer, seconds=0, recordings=[], trashedRecordings=[];
function formatTime(s){return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0');}
function renderRecordings(){const filter=$('#recordFilter').value;const visible=filter==='Todas'?recordings:filter==='personalizada'?recordings.filter(item=>item.custom):recordings.filter(item=>item.subject===filter);$('#recordingsList').innerHTML=visible.length?visible.map(item=>`<div class="audio-item"><span>🎙</span><span>${item.title}</span><span class="recording-subject">${item.subject}</span><audio controls src="${item.url}"></audio><button class="delete-recording" data-id="${item.id}">🗑</button></div>`).join(''):'<p class="small-status">Nenhuma gravação nesta matéria ainda.</p>';$$('.delete-recording').forEach(button=>button.onclick=()=>{const index=recordings.findIndex(item=>item.id===button.dataset.id);trashedRecordings.unshift(recordings.splice(index,1)[0]);renderRecordings();renderTrash();});}
function renderTrash(){$('#trashCount').textContent=trashedRecordings.length;$('#trashList').innerHTML=trashedRecordings.length?trashedRecordings.map(item=>`<div class="audio-item"><span>🎙</span><span>${item.title}</span><span class="recording-subject">${item.subject}</span><div class="trash-actions"><button data-restore="${item.id}">Recuperar</button><button class="remove-forever" data-remove="${item.id}">Apagar</button></div></div>`).join(''):'<p class="small-status">A lixeira está vazia.</p>';$$('[data-restore]').forEach(button=>button.onclick=()=>{const index=trashedRecordings.findIndex(item=>item.id===button.dataset.restore);recordings.unshift(trashedRecordings.splice(index,1)[0]);renderRecordings();renderTrash();});$$('[data-remove]').forEach(button=>button.onclick=()=>{const index=trashedRecordings.findIndex(item=>item.id===button.dataset.remove);const [item]=trashedRecordings.splice(index,1);URL.revokeObjectURL(item.url);renderTrash();});}
const deleteSubjectButton=document.createElement('button');deleteSubjectButton.type='button';deleteSubjectButton.className='delete-subject-button hidden';deleteSubjectButton.textContent='Excluir nome da matéria';$('#recordSubjectSelect').after(deleteSubjectButton);
function updateDeleteSubjectButton(){const selected=$('#recordSubjectSelect').selectedOptions[0];deleteSubjectButton.classList.toggle('hidden',!selected?.dataset.customSubject);}
function addCustomRecordingSubject(){const input=$('#customSubject'),subject=input.value.trim();if(!subject)return;[$('#recordSubjectSelect'),$('#recordFilter')].forEach(select=>{if(![...select.options].some(option=>option.value===subject)){const option=document.createElement('option');option.value=subject;option.textContent=subject;option.dataset.customSubject='true';select.insertBefore(option,select.querySelector('option[value="personalizada"]'));}});$('#recordSubjectSelect').value=subject;input.value='';input.classList.add('hidden');updateDeleteSubjectButton();}
$('#recordSubjectSelect').onchange=()=>{$('#customSubject').classList.toggle('hidden',$('#recordSubjectSelect').value!=='personalizada');updateDeleteSubjectButton();};
deleteSubjectButton.onclick=()=>{const subject=$('#recordSubjectSelect').value;if(!$('#recordSubjectSelect').selectedOptions[0]?.dataset.customSubject)return;[$('#recordSubjectSelect'),$('#recordFilter')].forEach(select=>[...select.options].find(option=>option.value===subject)?.remove());$('#recordSubjectSelect').value='Matemática';updateDeleteSubjectButton();};
$('#customSubject').onchange=addCustomRecordingSubject;
$('#customSubject').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();addCustomRecordingSubject();}};
$('#recordFilter').onchange=renderRecordings;
$('#toggleTrash').onclick=()=>{$('#trashPanel').classList.toggle('hidden');renderTrash();};
$('#recordButton').onclick=async()=>{if(recorder?.state==='recording'){recorder.stop();return;}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>chunks.push(e.data);recorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());clearInterval(recordTimer);$('#recordButton').classList.remove('stop');$('#recordButton').textContent='●';$('#recordVisual').classList.remove('recording');$('#recordTitle').textContent='Gravação salva!';$('#recordStatus').textContent='Você pode ouvir ou gravar outra.';const blob=new Blob(chunks,{type:'audio/webm'}),url=URL.createObjectURL(blob),isCustom=$('#recordSubjectSelect').value==='personalizada',subject=isCustom?$('#customSubject').value.trim()||'Nome da matéria':$('#recordSubjectSelect').value;recordings.unshift({id:crypto.randomUUID(),title:`Gravação ${new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}`,subject,custom:isCustom,url});renderRecordings();};recorder.start();seconds=0;$('#recordTime').textContent='00:00';recordTimer=setInterval(()=>$('#recordTime').textContent=formatTime(++seconds),1000);$('#recordButton').classList.add('stop');$('#recordButton').textContent='■';$('#recordVisual').classList.add('recording');$('#recordTitle').textContent='Gravando...';$('#recordStatus').textContent='Toque no quadrado para finalizar.';}catch(err){$('#recordStatus').textContent='Não foi possível usar o microfone. Verifique a permissão do navegador.';}};
renderRecordings();renderTrash();

let subjectPdfs = [];
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char])); }
function renderLibrary() { $('#libraryGrid').innerHTML = subjectPdfs.map(item=>`<article class="pdf-card"><span class="pdf-icon">📄</span><strong title="${escapeHtml(item.name)}">${escapeHtml(item.name)}</strong><small>${escapeHtml(item.subject)}</small><a href="${item.url}" download="${escapeHtml(item.name)}">Baixar PDF</a></article>`).join(''); }
$('#libraryFiles').onchange=e=>{const files=[...e.target.files];if(!files.length)return;const subject=$('#subjectSelect').value;subjectPdfs.push(...files.map(file=>({name:file.name,subject,url:URL.createObjectURL(file)})));renderLibrary();$('#libraryStatus').textContent=`${files.length} PDF(s) adicionado(s) em ${subject}.`;e.target.value='';};
$('#schoolSyncButton').onclick=()=>alert('Para baixar automaticamente os materiais do Escola Paraná, será preciso conectar uma integração oficial autorizada pela sua escola. Não informe sua senha no caderno digital.');
const exportButton = $('#exportButton');
if (exportButton) exportButton.onclick=()=>{saveCurrent();window.print();};
$('#pdfFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(!window.pdfjsLib){$('#pdfStatus').textContent='Não foi possível carregar o leitor de PDF. Verifique sua conexão.';return;}$('#pdfStatus').textContent='Lendo o PDF...';try{const data=await file.arrayBuffer(),pdf=await pdfjsLib.getDocument({data}).promise;let text='';for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i),content=await page.getTextContent();text+=content.items.map(x=>x.str).join(' ')+'\n\n';}text=text.replace(/(?:https?:\/\/|www\.)\S+/gi,'').replace(/\b\S+@\S+\.\S+\b/g,'').replace(/\n{3,}/g,'\n\n').trim();$('#transcriptionText').value=text;$('#transcriptionCard').classList.remove('hidden');$('#pdfStatus').textContent=`${pdf.numPages} página(s) transcrita(s), sem links.`;}catch(err){$('#pdfStatus').textContent='Não consegui ler este PDF. Tente outro arquivo.';}};
$('#copyText').onclick=async()=>{try{await navigator.clipboard.writeText($('#transcriptionText').value);$('#copyText').textContent='Texto copiado!';setTimeout(()=>$('#copyText').textContent='Copiar texto',1500);}catch{}};
$('#addTextToNotebook').onclick=()=>{saveCurrent();const pages=activeNotebook().pages;pages.push({title:'Material transcrito',content:'<p class="date">MATERIAL DE ESTUDO</p><h2>Texto transcrito</h2><p>'+$('#transcriptionText').value.replace(/\n/g,'</p><p>')+'</p>',stickers:[]});loadPage(pages.length-1);document.querySelector('[data-tab="caderno"]').click();};
