const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
let installAppPrompt=null;
if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));}
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installAppPrompt=event;$('#installAppButton').classList.add('available');});
window.addEventListener('appinstalled',()=>{installAppPrompt=null;$('#installAppButton').classList.remove('available');$('#installHelp').classList.add('hidden');});
function showInstallHelp(){const isIos=/iPad|iPhone|iPod/.test(navigator.userAgent);$('#installHelpText').textContent=isIos?'No Safari, toque em Compartilhar e depois em “Adicionar à Tela de Início”.':'Abra o menu do navegador e escolha “Instalar aplicativo” ou “Adicionar à tela inicial”.';$('#installHelp').classList.remove('hidden');}
$('#installAppButton').onclick=async()=>{if(!installAppPrompt){showInstallHelp();return;}installAppPrompt.prompt();await installAppPrompt.userChoice;installAppPrompt=null;$('#installAppButton').classList.remove('available');};
$('#closeInstallHelp').onclick=()=>$('#installHelp').classList.add('hidden');
if(!window.matchMedia('(display-mode: standalone)').matches)$('#installAppButton').classList.add('available');
let paperType = 'lined', currentPage = 0, currentNotebook = 0;
const notebookStorage = 'caderno-digital-notebooks';
let notebooks;
try { notebooks = JSON.parse(localStorage.getItem(notebookStorage)); } catch { notebooks = null; }
if (!Array.isArray(notebooks) || !notebooks.length) notebooks = [{ title: 'Meu caderno', cover: 'coral', paperType: 'lined', pages: [{ title: 'Página 1', content: $('#paperContent').innerHTML, stickers: [] }] }];
const legacyCoverMap = {animation:'netflix',series:'disney',cinema:'apple-tv',fantasy:'crunchyroll',space:'prime-video',mystery:'max','magic-school':'globoplay','hero-city':'pluto-tv','galaxy-saga':'netflix','pixel-world':'disney','ocean-adventure':'prime-video','detective-club':'max'};
notebooks.forEach(notebook=>{if(legacyCoverMap[notebook.cover])notebook.cover=legacyCoverMap[notebook.cover];});
notebooks.forEach(notebook=>{if(!notebook.id)notebook.id=crypto.randomUUID();});
try { localStorage.setItem(notebookStorage, JSON.stringify(notebooks)); } catch {}
const emojiStickerPack = [['😀','Sorriso','emojis'],['😂','Rindo','emojis'],['😍','Apaixonado','emojis'],['🤓','Estudando','emojis'],['🤔','Pensando','emojis'],['🥳','Comemorando','emojis'],['👏','Parabéns','emojis'],['👍','Gostei','emojis'],['❤️','Coração','emojis'],['🔥','Muito bom','emojis'],['💡','Ideia','emojis'],['✅','Concluído','emojis'],['📌','Importante','emojis'],['📝','Anotação','emojis'],['⏰','Lembrete','emojis'],['🎯','Meta','emojis']];
let customStickers=[];try{customStickers=JSON.parse(localStorage.getItem('caderno-digital-custom-stickers')||'[]');}catch{}
let stickerData = [
  ['📚','Livros','escola'],['✏️','Lápis','escola'],['🧠','Ideias','escola'],['💻','Computador','escola'],['🖥️','Monitor','escola'],['🔬','Ciência','escola'],['📐','Geometria','escola'],['🎓','Formatura','escola'],
  ['🌈','Arco-íris','diversao'],['🦄','Unicórnio','diversao'],['🎧','Música','diversao'],['⭐','Estrela','diversao'],['🎮','Game','diversao'],['🛼','Patins','diversao'],['🍓','Morango','natureza'],['🌻','Flor','natureza'],['🪴','Planta','natureza'],['🦋','Borboleta','natureza'],...emojiStickerPack,...customStickers.map(item=>[item.symbol,item.name,'criados'])
];

function activeNotebook() { return notebooks[currentNotebook]; }
function persistNotebooks() { try { localStorage.setItem(notebookStorage, JSON.stringify(notebooks)); } catch {} scheduleCloudSave(); }
function saveCurrent() { const page=activeNotebook().pages[currentPage]; page.content = $('#paperContent').innerHTML; page.stickers = $$('.placed-sticker').map(el => ({emoji:el.textContent,x:el.style.left,y:el.style.top}));if($('#drawingCanvas')?.width)page.drawing=$('#drawingCanvas').toDataURL('image/png'); persistNotebooks(); }
function renderNotebooks() { $('#notebookList').innerHTML = notebooks.map((n,i)=>`<div class="notebook-list-item"><button class="notebook-select ${i===currentNotebook?'active':''}" data-notebook="${i}"><span class="notebook-dot ${n.cover} ${n.cover}-cover" aria-hidden="true"></span><span class="notebook-name">${escapeHtml(n.title)}</span></button><button class="rename-notebook" data-rename-notebook="${i}" aria-label="Renomear ${escapeHtml(n.title)}" title="Renomear caderno">✎</button><button class="delete-notebook" data-delete-notebook="${i}" aria-label="Excluir ${escapeHtml(n.title)}" title="Excluir caderno" ${notebooks.length===1?'disabled':''}>🗑</button></div>`).join(''); $$('.notebook-select').forEach(b=>b.onclick=()=>loadNotebook(+b.dataset.notebook));$$('.rename-notebook').forEach(button=>button.onclick=()=>{const index=+button.dataset.renameNotebook,currentTitle=notebooks[index].title,newTitle=prompt('Qual será o novo nome do caderno?',currentTitle);if(!newTitle?.trim())return;notebooks[index].title=newTitle.trim();persistNotebooks();renderNotebooks();});$$('.delete-notebook').forEach(button=>button.onclick=()=>deleteNotebook(+button.dataset.deleteNotebook)); }
function deleteNotebook(index){if(notebooks.length===1)return;const notebook=notebooks[index];if(!confirm(`Excluir o caderno “${notebook.title}” e todas as suas folhas?`))return;saveCurrent();notebooks.splice(index,1);if(index<currentNotebook)currentNotebook--;else if(currentNotebook>=notebooks.length)currentNotebook=notebooks.length-1;persistNotebooks();loadNotebook(currentNotebook,false);}
function renderPages() { const pages=activeNotebook().pages;$('#pageList').innerHTML=pages.map((p,i)=>`<div class="page-list-item"><button class="page-select ${i===currentPage?'active':''}" data-page="${i}">▤ ${escapeHtml(p.title)}</button><button class="delete-page" data-delete-page="${i}" aria-label="Excluir ${escapeHtml(p.title)}" title="Excluir página" ${pages.length===1?'disabled':''}>✕</button></div>`).join('');$$('[data-page]').forEach(button=>button.onclick=()=>loadPage(+button.dataset.page));$$('[data-delete-page]').forEach(button=>button.onclick=()=>deletePage(+button.dataset.deletePage)); }
function deletePage(index){const pages=activeNotebook().pages;if(pages.length===1)return;const page=pages[index];if(!confirm(`Excluir ${page.title}?`))return;saveCurrent();pages.splice(index,1);pages.forEach((item,i)=>item.title=`Página ${i+1}`);if(index<currentPage)currentPage--;else if(currentPage>=pages.length)currentPage=pages.length-1;persistNotebooks();loadPage(currentPage,false);}
function loadPage(i, save=true) { if(save) saveCurrent(); currentPage=i; const p=activeNotebook().pages[i]; $('#paperContent').innerHTML=p.content; $('#stickerLayer').innerHTML=''; p.stickers.forEach(s=>placeSticker(s.emoji,s.x,s.y)); renderPages();requestAnimationFrame(()=>loadPageDrawing(p.drawing)); }
function loadNotebook(i, save=true) { if(save)saveCurrent(); currentNotebook=i; currentPage=0; const n=activeNotebook(); paperType=n.paperType; $('#notebook').className='notebook '+n.cover+'-cover'; $('#paper').className='paper '+paperType+'-paper'; $$('.cover-choice').forEach(b=>b.classList.toggle('selected',b.dataset.cover===n.cover)); $$('.paper-option').forEach(b=>b.classList.toggle('selected',b.dataset.paper===paperType)); renderNotebooks(); loadPage(0,false); }
let printNotebookIndex = 0, printPageIndex = 0;
function updatePrintPreview() { const notebook=notebooks[printNotebookIndex], page=notebook.pages[printPageIndex]; const paper=$('#printPaper'); paper.className='paper '+notebook.paperType+'-paper'; paper.innerHTML=`<div class="paper-content">${page.content}</div><div class="sticker-layer">${page.stickers.map(s=>`<span class="placed-sticker" style="left:${s.x};top:${s.y}">${s.emoji}</span>`).join('')}</div>`; }
function renderPrintOptions() { const notebookSelect=$('#printNotebookSelect'), pageSelect=$('#printPageSelect'); if (!notebookSelect || !pageSelect) return; if(printNotebookIndex>=notebooks.length) printNotebookIndex=0; notebookSelect.innerHTML=notebooks.map((n,i)=>`<option value="${i}">${n.title}</option>`).join(''); notebookSelect.value=printNotebookIndex; const notebook=notebooks[printNotebookIndex]; if(printPageIndex>=notebook.pages.length) printPageIndex=0; pageSelect.innerHTML=notebook.pages.map((p,i)=>`<option value="${i}">${p.title}</option>`).join(''); pageSelect.value=printPageIndex; updatePrintPreview(); }
function placeSticker(emoji, x='42%', y='42%') { const el=document.createElement('span'); el.className='placed-sticker'; el.textContent=emoji; el.style.left=x; el.style.top=y; el.setAttribute('aria-label','Adesivo '+emoji); enableDrag(el); $('#stickerLayer').append(el); }
function enableDrag(el) { let sx,sy,ox,oy; el.addEventListener('pointerdown',e=>{e.preventDefault();el.setPointerCapture(e.pointerId);sx=e.clientX;sy=e.clientY;ox=el.offsetLeft;oy=el.offsetTop;el.style.cursor='grabbing';}); el.addEventListener('pointermove',e=>{if(!el.hasPointerCapture(e.pointerId))return;const layer=$('#stickerLayer'), maxX=layer.clientWidth-el.offsetWidth, maxY=layer.clientHeight-el.offsetHeight;el.style.left=Math.max(0,Math.min(maxX,ox+e.clientX-sx))+'px';el.style.top=Math.max(0,Math.min(maxY,oy+e.clientY-sy))+'px';}); el.addEventListener('pointerup',e=>{el.releasePointerCapture(e.pointerId);el.style.cursor='grab';saveCurrent();}); el.addEventListener('dblclick',()=>{el.remove();saveCurrent();}); }

$$('.tab-panel').forEach(panel=>{panel.setAttribute('role','tabpanel');panel.setAttribute('aria-labelledby',`tab-${panel.id}`);panel.tabIndex=-1;});
$$('.nav-item').forEach(button=>{button.id=`tab-${button.dataset.tab}`;button.addEventListener('click',()=>{if($('#internalSiteViewer')&&!$('#internalSiteViewer').classList.contains('hidden'))closeInternalSite();saveCurrent();$$('.nav-item').forEach(b=>{const selected=b===button;b.classList.toggle('active',selected);b.setAttribute('aria-selected',String(selected));b.tabIndex=selected?0:-1;});$$('.tab-panel').forEach(p=>{const active=p.id===button.dataset.tab;p.classList.toggle('active',active);p.setAttribute('aria-hidden',String(!active));});if(button.dataset.tab==='imprimir')renderPrintOptions();setMobileMenu(false);window.scrollTo({top:0,behavior:document.body.classList.contains('reduce-motion')?'auto':'smooth'});});button.addEventListener('keydown',event=>{if(!['ArrowDown','ArrowUp','Home','End'].includes(event.key))return;event.preventDefault();const tabs=$$('.nav-item'),index=tabs.indexOf(button);const target=event.key==='Home'?tabs[0]:event.key==='End'?tabs.at(-1):tabs[(index+(event.key==='ArrowDown'?1:-1)+tabs.length)%tabs.length];target.focus();target.click();});});
$$('.tab-panel').forEach(panel=>panel.setAttribute('aria-hidden',String(!panel.classList.contains('active'))));

const canvaConnectionStorage='caderno-digital-canva-connected';
function renderCanvaConnection(){const connected=localStorage.getItem(canvaConnectionStorage)==='true';$('#canvaConnectView').classList.toggle('hidden',connected);$('#canvaWorkspace').classList.toggle('hidden',!connected);$('#finishCanvaConnection').classList.add('hidden');if(connected&&!$('#canvaFrame').getAttribute('src'))$('#canvaFrame').src='https://www.canva.com/';if(!connected)$('#canvaFrame').removeAttribute('src');}
$('#connectCanva').onclick=()=>{const canvaWindow=window.open('https://www.canva.com/login/','canva-account-login','popup,width=1100,height=760');if(!canvaWindow){$('#canvaStatus').textContent='O navegador bloqueou a janela do Canva. Permita janelas pop-up e tente novamente.';return;}$('#finishCanvaConnection').classList.remove('hidden');$('#canvaStatus').textContent='Entre no Canva e depois clique em “Já entrei — concluir vínculo”.';};
$('#finishCanvaConnection').onclick=()=>{localStorage.setItem(canvaConnectionStorage,'true');$('#canvaStatus').textContent='Canva vinculado neste navegador.';renderCanvaConnection();};
$('#disconnectCanva').onclick=()=>{localStorage.removeItem(canvaConnectionStorage);$('#canvaStatus').textContent='Canva desvinculado do Caderno Digital.';renderCanvaConnection();};
$('#reloadCanva').onclick=()=>{$('#canvaFrame').src='https://www.canva.com/';};
renderCanvaConnection();

const focusModeStorage='caderno-digital-focus-mode';
function applyFocusMode(active,announce=false){document.body.classList.toggle('focus-mode',active);$('#focusModeButton').setAttribute('aria-pressed',String(active));$('#focusModeLabel').textContent=active?'Sair do foco':'Modo foco';$('#focusModeButton').querySelector('span[aria-hidden]').textContent=active?'✕':'◎';if(announce)$('#focusModeStatus').textContent=active?'Modo foco ativado. Menus secundários foram ocultados.':'Modo foco desativado. Todos os menus estão visíveis.';try{localStorage.setItem(focusModeStorage,String(active));}catch{}}
applyFocusMode(localStorage.getItem(focusModeStorage)==='true');
$('#focusModeButton').onclick=()=>applyFocusMode(!document.body.classList.contains('focus-mode'),true);
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&document.body.classList.contains('focus-mode')&&$('#internalSiteViewer')?.classList.contains('hidden')){applyFocusMode(false,true);$('#focusModeButton').focus();}});
const focusScheduleStorage='caderno-digital-focus-schedule';let focusSchedule=[];
try{focusSchedule=JSON.parse(localStorage.getItem(focusScheduleStorage)||'[]');if(!Array.isArray(focusSchedule))focusSchedule=[];}catch{focusSchedule=[];}
function saveFocusSchedule(){try{localStorage.setItem(focusScheduleStorage,JSON.stringify(focusSchedule));}catch{}}
function renderFocusSchedule(){const list=$('#focusScheduleList');if(!focusSchedule.length){list.innerHTML='<p class="focus-schedule-empty">Nenhuma atividade adicionada.</p>';return;}list.innerHTML=[...focusSchedule].sort((a,b)=>a.time.localeCompare(b.time)).map(item=>`<div class="focus-schedule-item ${item.done?'done':''}"><input type="checkbox" data-focus-done="${item.id}" ${item.done?'checked':''} aria-label="Marcar ${escapeHtml(item.task)} como concluída"><span><strong>${escapeHtml(item.task)}</strong><small>${escapeHtml(item.time)} · ${item.duration} minutos</small></span><button type="button" data-focus-delete="${item.id}" aria-label="Excluir ${escapeHtml(item.task)}">✕</button></div>`).join('');$$('[data-focus-done]').forEach(input=>input.onchange=()=>{const item=focusSchedule.find(entry=>entry.id===input.dataset.focusDone);if(item){item.done=input.checked;saveFocusSchedule();renderFocusSchedule();}});$$('[data-focus-delete]').forEach(button=>button.onclick=()=>{focusSchedule=focusSchedule.filter(item=>item.id!==button.dataset.focusDelete);saveFocusSchedule();renderFocusSchedule();$('#focusScheduleStatus').textContent='Atividade excluída do cronograma.';});}
$('#focusScheduleForm').onsubmit=event=>{event.preventDefault();const task=$('#focusTask').value.trim(),time=$('#focusTaskTime').value,duration=Math.max(5,Math.min(240,Number($('#focusTaskDuration').value)||30));if(!task||!time)return;focusSchedule.push({id:crypto.randomUUID(),task,time,duration,done:false});saveFocusSchedule();renderFocusSchedule();event.target.reset();$('#focusTaskDuration').value=30;$('#focusScheduleStatus').textContent='Atividade adicionada ao cronograma.';$('#focusTask').focus();};
$('#toggleFocusSchedule').onclick=()=>{const collapsed=$('#focusSchedule').classList.toggle('collapsed');$('#toggleFocusSchedule').textContent=collapsed?'Expandir':'Recolher';$('#toggleFocusSchedule').setAttribute('aria-expanded',String(!collapsed));};renderFocusSchedule();

const accessibilityStorage='caderno-digital-accessibility';
let accessibilityPreferences={font:'normal',vision:'default',reduceMotion:window.matchMedia('(prefers-reduced-motion: reduce)').matches,underlineLinks:false,deafMode:false};
try{accessibilityPreferences={...accessibilityPreferences,...JSON.parse(localStorage.getItem(accessibilityStorage)||'{}')};}catch{}
function applyAccessibilityPreferences(){document.body.classList.remove('font-large','font-larger','vision-protanopia','vision-deuteranopia','vision-tritanopia','vision-achromatopsia','vision-high-contrast','reduce-motion','underline-controls','deaf-mode');if(accessibilityPreferences.font!=='normal')document.body.classList.add(`font-${accessibilityPreferences.font}`);if(accessibilityPreferences.vision!=='default')document.body.classList.add(`vision-${accessibilityPreferences.vision}`);document.body.classList.toggle('reduce-motion',accessibilityPreferences.reduceMotion);document.body.classList.toggle('underline-controls',accessibilityPreferences.underlineLinks);document.body.classList.toggle('deaf-mode',accessibilityPreferences.deafMode);$$('[data-font]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.font===accessibilityPreferences.font)));$('#visionMode').value=accessibilityPreferences.vision;$('#reduceMotion').checked=accessibilityPreferences.reduceMotion;$('#underlineLinks').checked=accessibilityPreferences.underlineLinks;$('#deafMode').checked=accessibilityPreferences.deafMode;const liveCaptions=$('#enableLiveCaptions');if(liveCaptions&&accessibilityPreferences.deafMode)liveCaptions.checked=true;try{localStorage.setItem(accessibilityStorage,JSON.stringify(accessibilityPreferences));}catch{}}
$('#accessibilityToggle').onclick=()=>{const panel=$('#accessibilityPanel'),willOpen=panel.classList.contains('hidden');panel.classList.toggle('hidden',!willOpen);$('#accessibilityToggle').setAttribute('aria-expanded',String(willOpen));if(willOpen)panel.querySelector('button,select,input')?.focus();};
$$('[data-font]').forEach(button=>button.onclick=()=>{accessibilityPreferences.font=button.dataset.font;applyAccessibilityPreferences();});
$('#visionMode').onchange=event=>{accessibilityPreferences.vision=event.target.value;applyAccessibilityPreferences();};
$('#reduceMotion').onchange=event=>{accessibilityPreferences.reduceMotion=event.target.checked;applyAccessibilityPreferences();};
$('#underlineLinks').onchange=event=>{accessibilityPreferences.underlineLinks=event.target.checked;applyAccessibilityPreferences();};
$('#deafMode').onchange=event=>{accessibilityPreferences.deafMode=event.target.checked;applyAccessibilityPreferences();};
applyAccessibilityPreferences();
['#recordStatus','#libraryStatus','#pdfStatus','#classroomStatus'].forEach(selector=>{const element=$(selector);if(element){element.setAttribute('role','status');element.setAttribute('aria-live','polite');}});
$('#recordTime').setAttribute('aria-label','Tempo da gravação');
$('#paperContent').setAttribute('aria-label','Conteúdo da folha atual. Pressione Enter para editar.');
$('#paperContent').setAttribute('role','textbox');
$('#paperContent').setAttribute('aria-multiline','true');
let pageSpeech;
$('#readPage').onclick=()=>{if(!('speechSynthesis'in window)){$('#speechStatus').textContent='A leitura em voz alta não está disponível neste navegador.';return;}window.speechSynthesis.cancel();const activePanel=$('.tab-panel.active'),text=activePanel?.innerText.replace(/\s+/g,' ').trim();if(!text){$('#speechStatus').textContent='Não há texto para ler nesta aba.';return;}pageSpeech=new SpeechSynthesisUtterance(text);pageSpeech.lang='pt-BR';pageSpeech.rate=.95;pageSpeech.onstart=()=>{$('#speechStatus').textContent='Leitura em voz alta iniciada.';$('#stopReading').disabled=false;};pageSpeech.onend=pageSpeech.onerror=()=>{$('#speechStatus').textContent='Leitura finalizada.';$('#stopReading').disabled=true;};window.speechSynthesis.speak(pageSpeech);};
$('#stopReading').onclick=()=>{window.speechSynthesis?.cancel();$('#speechStatus').textContent='Leitura interrompida.';$('#stopReading').disabled=true;};
$$('[data-phrase]').forEach(button=>button.onclick=()=>{$('#communicationText').value=button.dataset.phrase;$('#communicationText').focus();});
$('#speakCommunication').onclick=()=>{const text=$('#communicationText').value.trim();if(!text){$('#communicationStatus').textContent='Digite ou escolha uma mensagem primeiro.';$('#communicationText').focus();return;}if(!('speechSynthesis'in window)){$('#communicationStatus').textContent='A fala por texto não está disponível neste navegador.';return;}window.speechSynthesis.cancel();const message=new SpeechSynthesisUtterance(text);message.lang='pt-BR';message.rate=.9;message.onstart=()=>$('#communicationStatus').textContent='Reproduzindo a mensagem em voz alta.';message.onend=()=>$('#communicationStatus').textContent='Mensagem reproduzida.';message.onerror=()=>$('#communicationStatus').textContent='Não foi possível reproduzir a mensagem.';window.speechSynthesis.speak(message);};
$('#copyCommunication').onclick=async()=>{const text=$('#communicationText').value.trim();if(!text){$('#communicationStatus').textContent='Digite ou escolha uma mensagem primeiro.';return;}try{await navigator.clipboard.writeText(text);$('#communicationStatus').textContent='Mensagem copiada.';}catch{$('#communicationStatus').textContent='Não foi possível copiar a mensagem.';}};
$('#printNotebookSelect').onchange=e=>{printNotebookIndex=+e.target.value;printPageIndex=0;renderPrintOptions();};
$('#printPageSelect').onchange=e=>{printPageIndex=+e.target.value;updatePrintPreview();};
$('#printButton').onclick=()=>window.print();
function setMobileMenu(open){$('.sidebar').classList.toggle('open',open);$('#menuButton').setAttribute('aria-expanded',String(open));document.body.style.overflow=open&&window.innerWidth<=800?'hidden':'';}
$('#menuButton').onclick=()=>setMobileMenu(!$('.sidebar').classList.contains('open'));
$('#sidebarBackdrop').onclick=()=>setMobileMenu(false);
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&$('.sidebar').classList.contains('open')){setMobileMenu(false);$('#menuButton').focus();}});
window.addEventListener('resize',()=>{if(window.innerWidth>800)setMobileMenu(false);});
const firebaseConfig={apiKey:'AIzaSyDmmjyT_U4HsQ5VG95iLx9jwcnYBv4qTLI',authDomain:'ivory-forklift-507300-c1.firebaseapp.com',projectId:'ivory-forklift-507300-c1',storageBucket:'ivory-forklift-507300-c1.firebasestorage.app',messagingSenderId:'870562734780',appId:'1:870562734780:web:f4998283828f6cc516a6b9'};
let cloudAuth=null,cloudDb=null,cloudUser=null,cloudSaveTimer=null,cloudReady=false,cloudUnsubscribe=null;
const cloudClientId=sessionStorage.getItem('caderno-digital-cloud-client')||crypto.randomUUID();
sessionStorage.setItem('caderno-digital-cloud-client',cloudClientId);
function setCloudStatus(message){const status=$('#sideLoginStatus');if(status)status.textContent=message;}
function scheduleCloudSave(){if(!cloudUser||!cloudReady)return;clearTimeout(cloudSaveTimer);cloudSaveTimer=setTimeout(saveNotebooksToCloud,900);}
async function saveNotebooksToCloud(){if(!cloudUser||!cloudReady)return;setCloudStatus('Salvando e sincronizando seus dados...');try{await cloudDb.collection('users').doc(cloudUser.uid).set({notebooks:JSON.parse(JSON.stringify(notebooks)),platformProgress:JSON.parse(JSON.stringify(platformProgress||{})),updatedAt:firebase.firestore.FieldValue.serverTimestamp(),updatedBy:cloudClientId},{merge:true});setCloudStatus('✓ Cadernos e progresso sincronizados em todos os aparelhos.');}catch(error){setCloudStatus(error?.code==='resource-exhausted'?'O caderno ficou grande demais para a nuvem. Apague desenhos muito pesados e tente novamente.':'Não foi possível salvar na nuvem agora. Suas alterações continuam salvas neste aparelho.');}}
function showCloudNotebooks(cloudNotebooks){if(!Array.isArray(cloudNotebooks)||!cloudNotebooks.length)return;notebooks=cloudNotebooks;currentNotebook=0;currentPage=0;const first=activeNotebook();paperType=first.paperType||'lined';$('#notebook').className='notebook '+first.cover+'-cover';$('#paper').className='paper '+paperType+'-paper';$$('.cover-choice').forEach(button=>button.classList.toggle('selected',button.dataset.cover===first.cover));$$('.paper-option').forEach(button=>button.classList.toggle('selected',button.dataset.paper===paperType));try{localStorage.setItem(notebookStorage,JSON.stringify(notebooks));}catch{}renderNotebooks();loadPage(0,false);}
function mergeNotebookCollections(remoteNotebooks,localNotebooks){const merged=[],seen=new Set();for(const source of [remoteNotebooks,localNotebooks])for(const original of source||[]){if(!original||!Array.isArray(original.pages))continue;const notebook=JSON.parse(JSON.stringify(original));if(!notebook.id)notebook.id=crypto.randomUUID();if(seen.has(notebook.id))continue;seen.add(notebook.id);merged.push(notebook);}return merged;}
async function startGoogleLogin(){saveCurrent();if(!cloudAuth){setCloudStatus('A conexão com a nuvem ainda está carregando. Tente novamente em alguns segundos.');return;}if(cloudUser){await cloudAuth.signOut();return;}setCloudStatus('Abrindo a página segura do Google...');const provider=new firebase.auth.GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});try{await cloudAuth.signInWithPopup(provider);}catch(error){if(['auth/popup-blocked','auth/operation-not-supported-in-this-environment'].includes(error?.code)){setCloudStatus('Abrindo o Google em uma página segura...');try{await cloudAuth.signInWithRedirect(provider);return;}catch{}}setCloudStatus(error?.code==='auth/popup-closed-by-user'?'A janela do Google foi fechada antes de concluir a entrada.':'O Google não concluiu a entrada. Atualize a página e tente novamente.');}}
$('#sideGoogleLogin').onclick=startGoogleLogin;
if(window.firebase){firebase.initializeApp(firebaseConfig);cloudAuth=firebase.auth();cloudDb=firebase.firestore();cloudAuth.useDeviceLanguage();cloudAuth.getRedirectResult().catch(error=>setCloudStatus(error.code==='auth/unauthorized-domain'?'Este endereço ainda não foi autorizado para entrar com Google.':'O Google não concluiu a entrada. Toque no botão e tente novamente.'));cloudAuth.onAuthStateChanged(async user=>{if(cloudUnsubscribe){cloudUnsubscribe();cloudUnsubscribe=null;}cloudUser=user;cloudReady=false;if(!user){$('#sideGoogleLogin').innerHTML='<span aria-hidden="true">G</span> Continuar com Google';setCloudStatus('Entre com Google para salvar seus cadernos automaticamente na nuvem.');return;}$('#sideGoogleLogin').textContent='Sair da nuvem';setCloudStatus('Juntando os cadernos deste aparelho com os da nuvem...');const documentRef=cloudDb.collection('users').doc(user.uid);try{const snapshot=await documentRef.get(),remoteNotebooks=snapshot.exists?snapshot.data().notebooks:[];notebooks=mergeNotebookCollections(remoteNotebooks,notebooks);showCloudNotebooks(notebooks);cloudReady=true;await saveNotebooksToCloud();setCloudStatus(`✓ ${notebooks.length} caderno(s) sincronizado(s) em todos os aparelhos.`);cloudUnsubscribe=documentRef.onSnapshot(remote=>{const data=remote.data();if(!remote.exists||remote.metadata.hasPendingWrites||data?.updatedBy===cloudClientId||!Array.isArray(data?.notebooks))return;const combined=mergeNotebookCollections(data.notebooks,notebooks),received=combined.length>notebooks.length;showCloudNotebooks(combined);if(received){setCloudStatus('✓ Novos cadernos recebidos de outro aparelho.');scheduleCloudSave();}else setCloudStatus('✓ Alterações recebidas de outro aparelho.');},()=>setCloudStatus('A sincronização em tempo real foi interrompida. Verifique sua internet.'));}catch{cloudReady=true;setCloudStatus('Conta conectada, mas a nuvem ainda não respondeu. Tente novamente em instantes.');}});}
else setCloudStatus('Não foi possível carregar a conexão com a nuvem. Verifique sua internet.');
let cloudTypingTimer=null;
$('#paperContent').addEventListener('input',()=>{activeNotebook().pages[currentPage].content=$('#paperContent').innerHTML;clearTimeout(cloudTypingTimer);cloudTypingTimer=setTimeout(persistNotebooks,700);});
$$('.cover-choice').forEach(b=>b.onclick=()=>{ $$('.cover-choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');activeNotebook().cover=b.dataset.cover;$('#notebook').className='notebook '+b.dataset.cover+'-cover'; persistNotebooks(); renderNotebooks(); });
$$('.paper-option').forEach(b=>b.onclick=()=>{paperType=b.dataset.paper;activeNotebook().paperType=paperType;$$('.paper-option').forEach(x=>x.classList.toggle('selected',x===b));$('#paper').className='paper '+paperType+'-paper';persistNotebooks();});
$('#newPage').onclick=()=>{saveCurrent();const pages=activeNotebook().pages;pages.push({title:'Página '+(pages.length+1),content:'<p class="date">NOVA PÁGINA</p><h2>Minha nova ideia ✦</h2><p>Comece a escrever aqui...</p>',stickers:[]});loadPage(pages.length-1);};
const drawingCanvas=$('#drawingCanvas'),drawingContext=drawingCanvas.getContext('2d');
let drawing=false,lastDrawPoint=null,penColor='#292540',penSize=4,penTool='draw';
let savedTextRange=null;
const fontRow=document.createElement('label');fontRow.className='pen-font-row';fontRow.htmlFor='writingFont';fontRow.innerHTML='Fonte <select id="writingFont"><option value="DM Sans">DM Sans</option><option value="Fraunces">Fraunces</option><option value="Arial">Arial</option><option value="Georgia">Georgia</option><option value="Verdana">Verdana</option><option value="Trebuchet MS">Trebuchet</option><option value="Comic Sans MS">Divertida</option><option value="Courier New">Máquina de escrever</option><option value="Times New Roman">Clássica</option></select>';$('.pen-colors').after(fontRow);
document.addEventListener('selectionchange',()=>{const selection=window.getSelection();if(selection?.rangeCount&&$('#paperContent').contains(selection.anchorNode))savedTextRange=selection.getRangeAt(0).cloneRange();});
function restoreTextSelection(){const editor=$('#paperContent'),selection=window.getSelection();editor.focus();if(savedTextRange&&editor.contains(savedTextRange.commonAncestorContainer)){selection.removeAllRanges();selection.addRange(savedTextRange);}}
function sizeDrawingCanvas(){const paper=$('#paper');if(paper.clientWidth<10||paper.clientHeight<10)return;const width=Math.round(paper.clientWidth),height=Math.round(paper.clientHeight),ratio=Math.max(1,window.devicePixelRatio||1);if(drawingCanvas.width===Math.round(width*ratio)&&drawingCanvas.height===Math.round(height*ratio))return;const previous=drawingCanvas.width?drawingCanvas.toDataURL('image/png'):'';drawingCanvas.width=Math.round(width*ratio);drawingCanvas.height=Math.round(height*ratio);drawingContext.setTransform(ratio,0,0,ratio,0,0);if(previous){const image=new Image();image.onload=()=>drawingContext.drawImage(image,0,0,width,height);image.src=previous;}}
function loadPageDrawing(data){sizeDrawingCanvas();drawingContext.clearRect(0,0,drawingCanvas.clientWidth,drawingCanvas.clientHeight);if(!data)return;const image=new Image();image.onload=()=>drawingContext.drawImage(image,0,0,drawingCanvas.clientWidth,drawingCanvas.clientHeight);image.src=data;}
function setPenTool(tool){penTool=tool;const drawingActive=tool!=='text';drawingCanvas.classList.toggle('active',drawingActive);$('#paper').classList.toggle('drawing-active',drawingActive);$('#drawingMode').classList.toggle('active',tool==='draw');$('#eraserMode').classList.toggle('active',tool==='erase');$('#textWritingMode').classList.toggle('active',tool==='text');$('#penStatus').textContent=tool==='text'?'Modo escrita ativado. Toque na folha para digitar.':tool==='erase'?'Borracha ativada. Passe sobre os traços.':'Modo desenho ativado.';if(tool==='text'){$('#paperContent').focus();}}
function canvasPoint(event){const rect=drawingCanvas.getBoundingClientRect();return{x:event.clientX-rect.left,y:event.clientY-rect.top};}
drawingCanvas.addEventListener('pointerdown',event=>{if(penTool==='text')return;event.preventDefault();drawing=true;lastDrawPoint=canvasPoint(event);drawingCanvas.setPointerCapture(event.pointerId);});
drawingCanvas.addEventListener('pointermove',event=>{if(!drawing)return;event.preventDefault();const point=canvasPoint(event);drawingContext.save();drawingContext.globalCompositeOperation=penTool==='erase'?'destination-out':'source-over';drawingContext.strokeStyle=penColor;drawingContext.lineWidth=penTool==='erase'?penSize*3:penSize;drawingContext.lineCap='round';drawingContext.lineJoin='round';drawingContext.beginPath();drawingContext.moveTo(lastDrawPoint.x,lastDrawPoint.y);drawingContext.lineTo(point.x,point.y);drawingContext.stroke();drawingContext.restore();lastDrawPoint=point;});
function finishDrawing(event){if(!drawing)return;drawing=false;lastDrawPoint=null;if(event?.pointerId!==undefined&&drawingCanvas.hasPointerCapture(event.pointerId))drawingCanvas.releasePointerCapture(event.pointerId);saveCurrent();}
drawingCanvas.addEventListener('pointerup',finishDrawing);drawingCanvas.addEventListener('pointercancel',finishDrawing);drawingCanvas.addEventListener('pointerleave',event=>{if(drawing&&event.buttons===0)finishDrawing(event);});
$$('[data-pen-color]').forEach(button=>{button.addEventListener('pointerdown',event=>event.preventDefault());button.onclick=()=>{penColor=button.dataset.penColor;$$('[data-pen-color]').forEach(item=>item.classList.toggle('active',item===button));if(penTool==='text'){const editor=$('#paperContent');editor.focus();document.execCommand('foreColor',false,penColor);$('#penStatus').textContent='Cor escolhida para escrever. Digite ou selecione um texto para aplicar.';}else{setPenTool('draw');}};});
$('#writingFont').onchange=event=>{setPenTool('text');restoreTextSelection();document.execCommand('fontName',false,event.target.value);saveCurrent();$('#penStatus').textContent=`Fonte ${event.target.options[event.target.selectedIndex].text} aplicada ao texto.`;};
$('#penSize').oninput=event=>{$('#penSizeValue').textContent=event.target.value;penSize=Number(event.target.value);};
$('#drawingMode').onclick=()=>setPenTool('draw');$('#eraserMode').onclick=()=>setPenTool('erase');$('#textWritingMode').onclick=()=>setPenTool('text');
$('#clearDrawing').onclick=()=>{if(!confirm('Deseja apagar todos os desenhos desta folha?'))return;drawingContext.clearRect(0,0,drawingCanvas.clientWidth,drawingCanvas.clientHeight);saveCurrent();$('#penStatus').textContent='Os desenhos desta folha foram apagados.';};
function closePenTools(){saveCurrent();$('#penToolbar').classList.add('hidden');setPenTool('text');draggableNotebookButton?.focus();}
$('#closePenToolbar').onclick=closePenTools;
const draggableNotebookButton=$('#draggableNotebookButton');
draggableNotebookButton.addEventListener('click',()=>{const toolbar=$('#penToolbar'),opening=toolbar.classList.contains('hidden');toolbar.classList.toggle('hidden',!opening);if(opening){sizeDrawingCanvas();setPenTool('draw');$('#drawingMode').focus();}else{setPenTool('text');}});
window.addEventListener('resize',sizeDrawingCanvas);sizeDrawingCanvas();requestAnimationFrame(()=>loadPageDrawing(activeNotebook().pages[currentPage].drawing));
$('#newNotebook').onclick=()=>{const title=prompt('Qual é o nome do novo caderno?', 'Novo caderno');if(!title?.trim())return;saveCurrent();notebooks.push({id:crypto.randomUUID(),title:title.trim(),cover:'lilac',paperType:'lined',pages:[{title:'Página 1',content:'<p class="date">NOVO CADERNO</p><h2>'+title.trim()+' ✦</h2><p>Comece a escrever aqui...</p>',stickers:[]}]});loadNotebook(notebooks.length-1);};
const initialNotebook = activeNotebook();
paperType = initialNotebook.paperType;
$('#notebook').className='notebook '+initialNotebook.cover+'-cover';
$('#paper').className='paper '+paperType+'-paper';
$$('.cover-choice').forEach(b=>b.classList.toggle('selected',b.dataset.cover===initialNotebook.cover));
$$('.paper-option').forEach(b=>b.classList.toggle('selected',b.dataset.paper===paperType));
renderNotebooks(); loadPage(0,false);

function renderStickers(category='todos'){const list=category==='todos'?stickerData:stickerData.filter(s=>s[2]===category);$('#stickerGallery').innerHTML=list.length?list.map(([emoji,name])=>`<button class="sticker-card" data-emoji="${escapeHtml(emoji)}" aria-label="Adicionar adesivo ${escapeHtml(name)}"><span class="emoji" aria-hidden="true">${escapeHtml(emoji)}</span><small>${escapeHtml(name)}</small></button>`).join(''):'<p class="small-status">Nenhum adesivo nesta categoria ainda.</p>';$$('.sticker-card').forEach(b=>b.onclick=()=>{placeSticker(b.dataset.emoji);saveCurrent();});}renderStickers();
$$('.sticker-filter').forEach(b=>b.onclick=()=>{$$('.sticker-filter').forEach(x=>x.classList.toggle('active',x===b));renderStickers(b.dataset.category);});

const emojiCategoryButton=document.createElement('button');emojiCategoryButton.className='sticker-filter';emojiCategoryButton.dataset.category='emojis';emojiCategoryButton.textContent='Emojis';
const createdCategoryButton=document.createElement('button');createdCategoryButton.className='sticker-filter';createdCategoryButton.dataset.category='criados';createdCategoryButton.textContent='Meus adesivos';
const createStickerButton=document.createElement('button');createStickerButton.id='createStickerButton';createStickerButton.className='primary-button';createStickerButton.textContent='＋ Criar adesivo';
const syncEmojiButton=document.createElement('button');syncEmojiButton.id='syncEmojiButton';syncEmojiButton.className='secondary-button';syncEmojiButton.textContent='↻ Sincronizar emojis';
$('#stickerGallery').before(Object.assign(document.createElement('div'),{id:'stickerCreator',className:'sticker-creator hidden',innerHTML:'<label for="customStickerSymbol">Emoji, símbolo ou texto curto</label><input id="customStickerSymbol" maxlength="4" placeholder="Ex.: 🌟"><label for="customStickerName">Nome do adesivo</label><input id="customStickerName" maxlength="30" placeholder="Ex.: Minha estrela"><button id="saveCustomSticker" class="primary-button">Salvar adesivo</button><p id="stickerCreatorStatus" class="small-status" role="status" aria-live="polite"></p>'}));
$('#stickerGallery').before(Object.assign(document.createElement('p'),{id:'emojiSyncStatus',className:'small-status'}));
$('.sticker-tabs').append(emojiCategoryButton,createdCategoryButton,createStickerButton,syncEmojiButton);
$$('.sticker-filter').forEach(b=>b.onclick=()=>{$$('.sticker-filter').forEach(x=>x.classList.toggle('active',x===b));renderStickers(b.dataset.category);});
createStickerButton.onclick=()=>{const creator=$('#stickerCreator'),open=creator.classList.contains('hidden');creator.classList.toggle('hidden',!open);if(open)$('#customStickerSymbol').focus();};
$('#saveCustomSticker').onclick=()=>{const symbol=$('#customStickerSymbol').value.trim(),name=$('#customStickerName').value.trim();if(!symbol||!name){$('#stickerCreatorStatus').textContent='Digite o adesivo e o nome.';return;}customStickers.push({symbol,name});localStorage.setItem('caderno-digital-custom-stickers',JSON.stringify(customStickers));stickerData.push([symbol,name,'criados']);$('#customStickerSymbol').value='';$('#customStickerName').value='';$('#stickerCreatorStatus').textContent='Adesivo criado e salvo.';createdCategoryButton.click();};
syncEmojiButton.onclick=()=>{stickerData=stickerData.filter(item=>item[2]!=='emojis');stickerData.push(...emojiStickerPack);localStorage.setItem('caderno-digital-emoji-sync',new Date().toISOString());$('#emojiSyncStatus').textContent=`${emojiStickerPack.length} emojis sincronizados com sucesso.`;emojiCategoryButton.click();};

const answers = {fotossíntese:'A fotossíntese é como a cozinha das plantas: usando luz do sol, água e gás carbônico, ela produz açúcar para ter energia e libera oxigênio. Acontece principalmente nas folhas, graças à clorofila.',equação:'Para resolver uma equação de 1º grau, deixe o x sozinho em um lado do sinal de igual. Exemplo: 2x + 4 = 10. Tire 4 dos dois lados: 2x = 6. Depois divida ambos por 2: x = 3.',resumo:'Para criar um bom resumo: 1) leia o assunto, 2) anote só as ideias principais com suas palavras, 3) use títulos e exemplos, e 4) releia tentando explicar sem olhar. Posso ajudar se você colar o texto aqui.',alura:'Nas aulas da Alura, pause quando surgir um conceito novo, anote a ideia principal e teste o que foi mostrado. Se você me disser o tema ou colar um trecho da aula, eu explico passo a passo com exemplos.',duolingo:'Posso ajudar nos seus estudos do Duolingo. Informe sua conta e o progresso no cartão Duolingo abaixo para salvá-los no Caderno Digital, ou diga qual idioma e assunto você está estudando.'};
function reply(question){const q=question.toLowerCase();if(q.includes('fotossíntese'))return answers.fotossíntese;if(q.includes('equação')||q.includes('primeiro grau'))return answers.equação;if(q.includes('resumo'))return answers.resumo;if(q.includes('alura'))return answers.alura;if(q.includes('duolingo'))return answers.duolingo;return 'Ótima pergunta! Para estudar esse assunto, comece identificando os conceitos principais e procurando um exemplo prático. Conte qual parte está mais difícil ou cole um trecho do material que eu explico de um jeito mais simples.';}
function addMessage(text,type,question=''){const m=document.createElement('div');m.className='message '+type;const content=document.createElement('span');content.textContent=text;m.append(content);if(type==='luma'&&question){const save=document.createElement('button');save.className='save-response-card';save.textContent='＋ Salvar como flashcard';save.onclick=()=>addResponseCard(question,text);m.append(save);}$('#chatBox').append(m);$('#chatBox').scrollTop=$('#chatBox').scrollHeight;}
$('#aiForm').onsubmit=e=>{e.preventDefault();const input=$('#aiQuestion'),q=input.value.trim();if(!q)return;addMessage(q,'user');input.value='';setTimeout(()=>addMessage(reply(q),'luma',q),250);};$$('.suggestions button').forEach(b=>b.onclick=()=>{$('#aiQuestion').value=b.dataset.question;$('#aiForm').requestSubmit();});

const responseCardsStorage='caderno-digital-response-cards',studyPlanStorage='caderno-digital-study-plan',platformProgressStorage='caderno-digital-platform-progress';
const aluraEmailField=$('#aluraCourse'),aluraEmailLabel=document.querySelector('label[for="aluraCourse"]'),aluraProgressField=$('#aluraProgress'),aluraProgressLabel=document.querySelector('label[for="aluraProgress"]');
aluraEmailField.id='aluraEmail';aluraEmailField.type='email';aluraEmailField.placeholder='seuemail@exemplo.com';aluraEmailField.removeAttribute('value');aluraEmailLabel.htmlFor='aluraEmail';aluraEmailLabel.textContent='E-mail da conta Alura';aluraProgressField.hidden=true;aluraProgressLabel.hidden=true;aluraProgressLabel.textContent='';
const duolingoEmailField=$('#duolingoLanguage'),duolingoEmailLabel=document.querySelector('label[for="duolingoLanguage"]'),duolingoProgressField=$('#duolingoStreak'),duolingoProgressLabel=document.querySelector('label[for="duolingoStreak"]');
duolingoEmailField.id='duolingoEmail';duolingoEmailField.type='email';duolingoEmailField.placeholder='seuemail@exemplo.com';duolingoEmailLabel.htmlFor='duolingoEmail';duolingoEmailLabel.textContent='E-mail da conta Duolingo';duolingoProgressField.id='duolingoProgress';duolingoProgressField.min='0';duolingoProgressField.max='100';duolingoProgressField.hidden=true;duolingoProgressLabel.htmlFor='duolingoProgress';duolingoProgressLabel.hidden=true;duolingoProgressLabel.textContent='';
let responseCards=[],studyPlan=[],platformProgress={aluraEmail:'',aluraProgress:'',duolingoEmail:'',duolingoProgress:''};
try{responseCards=JSON.parse(localStorage.getItem(responseCardsStorage)||'[]');}catch{}
try{studyPlan=JSON.parse(localStorage.getItem(studyPlanStorage)||'[]');}catch{}
try{platformProgress={...platformProgress,...JSON.parse(localStorage.getItem(platformProgressStorage)||'{}')};}catch{}
if(platformProgress.duolingoEmail==='teste.duolingo@example.com'){platformProgress.duolingoEmail='';platformProgress.duolingoProgress='';localStorage.setItem(platformProgressStorage,JSON.stringify(platformProgress));}
function renderResponseCards(){$('#responseCards').innerHTML=responseCards.length?responseCards.map(card=>`<article class="response-card flashcard" data-flashcard="${card.id}"><span class="flashcard-side-label">FRENTE</span><div class="flashcard-front"><h3>${escapeHtml(card.question)}</h3></div><div class="flashcard-back hidden"><p>${escapeHtml(card.answer)}</p></div><button class="flip-flashcard" data-flip-card="${card.id}" aria-expanded="false">↻ Ver verso</button><div class="flashcard-card-actions"><button data-edit-card="${card.id}">Editar</button><button data-remove-card="${card.id}" aria-label="Excluir flashcard ${escapeHtml(card.question)}">Excluir</button></div></article>`).join(''):'<p class="small-status">Nenhum flashcard salvo ainda.</p>';$$('[data-flip-card]').forEach(button=>button.onclick=()=>{const card=$(`[data-flashcard="${button.dataset.flipCard}"]`),showingBack=!card.querySelector('.flashcard-back').classList.contains('hidden');card.querySelector('.flashcard-front').classList.toggle('hidden',!showingBack);card.querySelector('.flashcard-back').classList.toggle('hidden',showingBack);card.querySelector('.flashcard-side-label').textContent=showingBack?'FRENTE':'VERSO';button.textContent=showingBack?'↻ Ver verso':'↻ Ver frente';button.setAttribute('aria-expanded',String(!showingBack));});$$('[data-edit-card]').forEach(button=>button.onclick=()=>{const card=responseCards.find(item=>item.id===button.dataset.editCard);if(!card)return;const question=prompt('Frente do flashcard:',card.question);if(!question?.trim())return;const answer=prompt('Verso do flashcard:',card.answer);if(!answer?.trim())return;card.question=question.trim();card.answer=answer.trim();localStorage.setItem(responseCardsStorage,JSON.stringify(responseCards));renderResponseCards();});$$('[data-remove-card]').forEach(button=>button.onclick=()=>{responseCards=responseCards.filter(card=>card.id!==button.dataset.removeCard);localStorage.setItem(responseCardsStorage,JSON.stringify(responseCards));renderResponseCards();});}
function addResponseCard(question,answer){responseCards.unshift({id:crypto.randomUUID(),question,answer});localStorage.setItem(responseCardsStorage,JSON.stringify(responseCards));renderResponseCards();$('#clearResponseCards').textContent='Flashcard salvo!';setTimeout(()=>$('#clearResponseCards').textContent='Limpar flashcards',1200);}
const addFlashcardButton=document.createElement('button');addFlashcardButton.id='addFlashcard';addFlashcardButton.className='primary-button';addFlashcardButton.textContent='＋ Adicionar um Flashcard';$('#clearResponseCards').before(addFlashcardButton);
const flashcardCount=document.createElement('p');flashcardCount.id='flashcardCount';flashcardCount.className='flashcard-count';flashcardCount.setAttribute('aria-live','polite');$('#responseCards').before(flashcardCount);function updateFlashcardCount(){flashcardCount.textContent=`${responseCards.length} flashcard${responseCards.length===1?' disponível':'s disponíveis'}`;}new MutationObserver(updateFlashcardCount).observe($('#responseCards'),{childList:true});updateFlashcardCount();
document.body.insertAdjacentHTML('beforeend','<dialog id="flashcardBatchDialog" class="flashcard-batch-dialog"><form method="dialog"><h2>Adicionar Flashcards</h2><p>Escolha quantos cartões deseja criar.</p><label for="flashcardQuantity">Quantidade</label><select id="flashcardQuantity"><option value="10">10 flashcards</option><option value="20">20 flashcards</option><option value="30">30 flashcards</option></select><label for="flashcardTopic">Assunto dos cartões</label><input id="flashcardTopic" maxlength="80" placeholder="Ex.: Fotossíntese" required><div><button value="cancel" class="secondary-button">Cancelar</button><button id="createFlashcardBatch" value="default" class="primary-button">Criar flashcards</button></div></form></dialog>');
addFlashcardButton.onclick=()=>{$('#flashcardBatchDialog').showModal();$('#flashcardTopic').focus();};
async function generateTopicFlashcards(topic,quantity){const endpoint='https://pt.wikipedia.org/w/api.php?'+new URLSearchParams({action:'query',generator:'search',gsrsearch:topic,gsrlimit:'6',prop:'extracts',explaintext:'1',exintro:'1',format:'json',origin:'*'}),response=await fetch(endpoint),data=await response.json(),pages=Object.values(data.query?.pages||{}),stopWords=new Set(['sobre','entre','também','ainda','desde','foram','forma','parte','quando','onde','como','para','pela','pelos','pelas','mais','muito','uma','alguns','algumas','possui','podem','sendo']);const candidates=[];for(const page of pages){const sentences=(page.extract||'').replace(/\([^)]*\)/g,'').split(/(?<=[.!?])\s+/).map(sentence=>sentence.trim()).filter(sentence=>sentence.length>=45&&sentence.length<=320);if(sentences[0])candidates.push({question:`O que é ${page.title}?`,answer:sentences[0]});for(const sentence of sentences.slice(1)){const words=sentence.match(/[A-Za-zÀ-ÖØ-öø-ÿ]{6,}/g)||[],keyword=words.filter(word=>!stopWords.has(word.toLowerCase())).sort((a,b)=>b.length-a.length)[0];if(!keyword)continue;candidates.push({question:`Complete a frase sobre ${topic}: ${sentence.replace(keyword,'_____')}`,answer:`${keyword}. Frase completa: ${sentence}`});}}if(!candidates.length)throw new Error('no-content');return Array.from({length:quantity},(_,index)=>({id:crypto.randomUUID(),...candidates[index%candidates.length],source:'Wikipédia'}));}
function fallbackTopicFlashcards(topic,quantity){const prompts=['O que é','Qual é a definição de','Quais são as principais características de','Por que é importante estudar','Dê um exemplo relacionado a','Quais são as partes principais de','Como funciona','Quais são as causas de','Quais são as consequências de','Faça um resumo de'];return Array.from({length:quantity},(_,index)=>({id:crypto.randomUUID(),question:`${prompts[index%prompts.length]} ${topic}?`,answer:`Revise suas anotações sobre ${topic} e edite este verso com a resposta.`}));}
$('#flashcardBatchDialog').addEventListener('close',async()=>{if($('#flashcardBatchDialog').returnValue!=='default')return;const quantity=Number($('#flashcardQuantity').value),topic=$('#flashcardTopic').value.trim();if(!topic||![10,20,30].includes(quantity))return;flashcardCount.textContent=`Gerando ${quantity} flashcards sobre ${topic}...`;addFlashcardButton.disabled=true;let cards;try{cards=await generateTopicFlashcards(topic,quantity);}catch{cards=fallbackTopicFlashcards(topic,quantity);}responseCards.unshift(...cards);localStorage.setItem(responseCardsStorage,JSON.stringify(responseCards));renderResponseCards();$('#flashcardTopic').value='';addFlashcardButton.disabled=false;addFlashcardButton.textContent='＋ Adicionar mais Flashcards';setTimeout(()=>flashcardCount.textContent=`✓ ${quantity} flashcards sobre ${topic} criados · ${responseCards.length} no total`,0);});
$('#clearResponseCards').onclick=()=>{if(!responseCards.length||!confirm('Deseja apagar todos os flashcards?'))return;responseCards=[];localStorage.setItem(responseCardsStorage,'[]');renderResponseCards();};
function renderStudyPlan(){$('#studyPlanList').innerHTML=studyPlan.length?studyPlan.map(item=>`<div class="study-plan-item ${item.done?'done':''}"><input type="checkbox" data-plan-done="${item.id}" ${item.done?'checked':''} aria-label="Concluir ${escapeHtml(item.task)}"><strong>${escapeHtml(item.day)}</strong><span>${escapeHtml(item.task)}</span><button data-remove-plan="${item.id}" aria-label="Excluir atividade ${escapeHtml(item.task)}">✕</button></div>`).join(''):'<p class="small-status">Seu plano está vazio. Adicione a primeira atividade.</p>';$$('[data-plan-done]').forEach(input=>input.onchange=()=>{const item=studyPlan.find(entry=>entry.id===input.dataset.planDone);item.done=input.checked;localStorage.setItem(studyPlanStorage,JSON.stringify(studyPlan));renderStudyPlan();});$$('[data-remove-plan]').forEach(button=>button.onclick=()=>{studyPlan=studyPlan.filter(item=>item.id!==button.dataset.removePlan);localStorage.setItem(studyPlanStorage,JSON.stringify(studyPlan));renderStudyPlan();});}
$('#studyPlanForm').onsubmit=event=>{event.preventDefault();const task=$('#studyTask').value.trim();if(!task)return;studyPlan.push({id:crypto.randomUUID(),task,day:$('#studyDay').value,done:false});localStorage.setItem(studyPlanStorage,JSON.stringify(studyPlan));$('#studyTask').value='';renderStudyPlan();};
$('#aluraEmail').value=platformProgress.aluraEmail||'';$('#aluraProgress').value=platformProgress.aluraProgress||'';$('#duolingoEmail').value=platformProgress.duolingoEmail||'';$('#duolingoProgress').value=platformProgress.duolingoProgress||'';
function renderPlatformDashboard(platform='alura'){const dashboard=platform==='alura'?$('#platformDashboard'):$('#duolingoDashboard');if(!dashboard)return;if(platform==='alura'){const progress=Math.max(0,Math.min(100,Number(platformProgress.aluraProgress)||0));dashboard.innerHTML=`<article class="platform-dashboard-card"><h3>Painel Alura</h3><p><strong>Conta:</strong> ${platformProgress.aluraEmail?escapeHtml(platformProgress.aluraEmail):'Nenhum e-mail informado'}</p><p><strong>Progresso registrado:</strong> ${progress}%</p><div class="progress-track" role="progressbar" aria-label="Progresso na Alura" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${progress}"><span style="width:${progress}%"></span></div></article>`;}else{const hasProgress=platformProgress.duolingoProgress!==''&&platformProgress.duolingoProgress!=null,progress=Math.max(0,Math.min(100,Number(platformProgress.duolingoProgress)||0));dashboard.innerHTML=`<article class="platform-dashboard-card"><h3>Painel Duolingo</h3><p><strong>Conta:</strong> ${platformProgress.duolingoEmail?escapeHtml(platformProgress.duolingoEmail):'Nenhum e-mail informado'}</p><p><strong>Progresso registrado:</strong> ${hasProgress?progress+'%':'Nenhum progresso informado'}</p>${hasProgress?`<div class="progress-track" role="progressbar" aria-label="Progresso no Duolingo" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${progress}"><span style="width:${progress}%"></span></div>`:''}</article>`;}}
async function loadAccountProgress(user){if(!user||!cloudDb)return;try{const snapshot=await cloudDb.collection('users').doc(user.uid).get(),saved=snapshot.data()?.platformProgress;if(saved){platformProgress={...platformProgress,...saved};localStorage.setItem(platformProgressStorage,JSON.stringify(platformProgress));$('#aluraEmail').value=platformProgress.aluraEmail||'';$('#aluraProgress').value=platformProgress.aluraProgress||'';$('#duolingoEmail').value=platformProgress.duolingoEmail||'';$('#duolingoProgress').value=platformProgress.duolingoProgress||'';renderPlatformDashboard('duolingo');$('#platformSyncStatus').textContent='✓ Dados de estudo carregados automaticamente da sua conta.';}}catch{}}
if(cloudAuth)cloudAuth.onAuthStateChanged(loadAccountProgress);
function savePlatformProgress(platform){if(platform==='Duolingo'){platformProgress={...platformProgress,duolingoEmail:$('#duolingoEmail').value.trim(),duolingoProgress:$('#duolingoProgress').value};}else{platformProgress={...platformProgress,aluraEmail:$('#aluraEmail').value.trim(),aluraProgress:$('#aluraProgress').value};}localStorage.setItem(platformProgressStorage,JSON.stringify(platformProgress));renderPlatformDashboard(platform.toLowerCase());const status=platform==='Duolingo'?$('#duolingoSyncStatus'):$('#platformSyncStatus');if(status)status.textContent=`Dados do ${platform} sincronizados dentro do Caderno Digital.`;scheduleCloudSave();}
$('#saveAlura').onclick=()=>savePlatformProgress('Alura');$('#saveDuolingo').onclick=()=>savePlatformProgress('Duolingo');$$('[data-view-platform]').forEach(button=>button.onclick=()=>renderPlatformDashboard(button.dataset.viewPlatform));renderPlatformDashboard();
[{container:'.alura-card',title:'Alura',url:'https://cursos.alura.com.br/dashboard'},{container:'.duolingo-card',title:'Duolingo',url:'https://www.duolingo.com/learn'}].forEach(platform=>{const button=document.createElement('button');button.type='button';button.className='platform-view-button';button.textContent=`Acessar ${platform.title} aqui dentro`;button.onclick=()=>openInternalSite(platform.url,platform.title);$(platform.container).append(button);});
const platformSyncArea=$('.platform-sync-area'),aluraTabMount=$('#aluraTabMount');
if(platformSyncArea&&aluraTabMount){aluraTabMount.append(platformSyncArea);platformSyncArea.hidden=false;platformSyncArea.style.display='block';const heading=platformSyncArea.querySelector('h2'),description=platformSyncArea.querySelector('h2 + p');if(heading)heading.textContent='Minha Alura';if(description)description.textContent='Registre sua conta e acesse a plataforma para continuar seus estudos.';}
const aluraConnectionStorage='caderno-digital-alura-connected',aluraCard=$('.alura-card');
if(aluraCard){aluraCard.insertAdjacentHTML('afterbegin','<span id="aluraConnectedBadge" class="khan-badge hidden">✓ Alura vinculada</span>');$('#saveAlura').textContent='Vincular Alura';$('#saveAlura').insertAdjacentHTML('afterend','<button id="finishAluraConnection" type="button" class="secondary-button hidden">Já entrei — concluir vínculo</button><button id="disconnectAlura" type="button" class="secondary-button hidden">Desvincular Alura</button>');}
function renderAluraConnection(){const connected=localStorage.getItem(aluraConnectionStorage)==='true';$('#aluraConnectedBadge')?.classList.toggle('hidden',!connected);$('#saveAlura')?.classList.toggle('hidden',connected);$('#disconnectAlura')?.classList.toggle('hidden',!connected);if(connected)$('#platformSyncStatus').textContent='✓ Conta Alura vinculada ao Caderno Digital.';}
if($('#saveAlura'))$('#saveAlura').onclick=()=>{const email=$('#aluraEmail').value.trim();if(!email||!$('#aluraEmail').checkValidity()){$('#platformSyncStatus').textContent='Digite um e-mail válido para vincular sua conta Alura.';$('#aluraEmail').focus();return;}const loginWindow=window.open('https://cursos.alura.com.br/loginForm','alura-account-login','popup,width=1100,height=760');if(!loginWindow){$('#platformSyncStatus').textContent='O navegador bloqueou a janela da Alura. Permita janelas pop-up e tente novamente.';return;}$('#finishAluraConnection').classList.remove('hidden');$('#platformSyncStatus').textContent='Entre na página oficial da Alura e depois clique em “Já entrei — concluir vínculo”.';};
if($('#finishAluraConnection'))$('#finishAluraConnection').onclick=()=>{savePlatformProgress('Alura');localStorage.setItem(aluraConnectionStorage,'true');$('#finishAluraConnection').classList.add('hidden');renderAluraConnection();};
if($('#disconnectAlura'))$('#disconnectAlura').onclick=()=>{if(!confirm('Desvincular sua conta Alura deste caderno?'))return;localStorage.removeItem(aluraConnectionStorage);renderAluraConnection();$('#platformSyncStatus').textContent='Conta Alura desvinculada. Seus cadernos continuam salvos.';};
renderAluraConnection();
const duolingoCard=$('.duolingo-card'),duolingoTabMount=$('#duolingoTabMount');
if(duolingoCard&&duolingoTabMount){duolingoTabMount.append(duolingoCard);duolingoCard.querySelector('h3').textContent='Minha conta Duolingo';$('#saveDuolingo').textContent='Vincular Duolingo';}
renderPlatformDashboard('duolingo');
renderResponseCards();renderStudyPlan();

const enemStorage='caderno-digital-enem';
let enemProfile={email:'',registrationStatus:'not-checked',areas:{}};
try{enemProfile={...enemProfile,...JSON.parse(localStorage.getItem(enemStorage)||'{}')};}catch{}
$('#enemEmail').value=enemProfile.email||'';$('#enemRegistrationStatus').value=enemProfile.registrationStatus||'not-checked';
$$('[data-enem-area]').forEach(input=>{input.checked=Boolean(enemProfile.areas?.[input.dataset.enemArea]);});
function renderEnemProgress(){const areas=$$('[data-enem-area]'),done=areas.filter(input=>input.checked).length,progress=Math.round(done/areas.length*100);$('#enemProgressText').textContent=`${progress}% concluído`;$('#enemProgress').setAttribute('aria-valuenow',progress);$('#enemProgress span').style.width=`${progress}%`;}
function saveEnemProfile(showMessage=true){enemProfile={email:$('#enemEmail').value.trim(),registrationStatus:$('#enemRegistrationStatus').value,areas:Object.fromEntries($$('[data-enem-area]').map(input=>[input.dataset.enemArea,input.checked]))};localStorage.setItem(enemStorage,JSON.stringify(enemProfile));renderEnemProgress();if(showMessage)$('#enemProfileStatus').textContent='Dados do ENEM salvos neste aparelho.';}
$('#saveEnemProfile').onclick=()=>{if($('#enemEmail').value&&!$('#enemEmail').checkValidity()){$('#enemProfileStatus').textContent='Digite um e-mail válido da sua conta gov.br.';$('#enemEmail').focus();return;}saveEnemProfile();};
$$('[data-enem-area]').forEach(input=>input.onchange=()=>saveEnemProfile(false));
$$('[data-enem-url]').forEach(button=>button.onclick=()=>openInternalSite(button.dataset.enemUrl,button.dataset.enemTitle));
$('#syncEnemOfficial').onclick=()=>{$('#enemSyncStatus').textContent='Canais oficiais do MEC/INEP atualizados. Seus dados pessoais continuam protegidos no gov.br.';};renderEnemProgress();

const readingStorage='caderno-digital-reading',leiaParanaUrl='https://leiaparana.odilo.us/',leiaParanaHelpUrl='https://professor.escoladigital.pr.gov.br/FAQ/plataformas_educacionais/leia_parana';
let readingProfile={email:'',book:'',progress:0,notes:''};
try{readingProfile={...readingProfile,...JSON.parse(localStorage.getItem(readingStorage)||'{}')};}catch{}
$('#readingSchoolEmail').value=readingProfile.email||'';$('#readingBookTitle').value=readingProfile.book||'';$('#readingProgress').value=Math.max(0,Math.min(100,Number(readingProfile.progress)||0));$('#readingNotes').value=readingProfile.notes||'';
function renderReadingProgress(){const progress=Math.max(0,Math.min(100,Number($('#readingProgress').value)||0));$('#readingProgressValue').textContent=`${progress}%`;$('#readingProgressTrack').setAttribute('aria-valuenow',progress);$('#readingProgressTrack span').style.width=`${progress}%`;}
$('#readingProgress').oninput=renderReadingProgress;renderReadingProgress();
$('#saveReadingProgress').onclick=()=>{const email=$('#readingSchoolEmail');if(email.value&&!email.checkValidity()){$('#readingSaveStatus').textContent='Digite um e-mail @escola válido.';email.focus();return;}readingProfile={email:email.value.trim(),book:$('#readingBookTitle').value.trim(),progress:Number($('#readingProgress').value),notes:$('#readingNotes').value.trim()};try{localStorage.setItem(readingStorage,JSON.stringify(readingProfile));$('#readingSaveStatus').textContent='Leitura e progresso salvos neste aparelho.';}catch{$('#readingSaveStatus').textContent='Não foi possível salvar neste navegador.';}};
$('#openLeiaParana').onclick=()=>openInternalSite(leiaParanaUrl,'Leia Paraná — Clube de Leitura');
$('#openLeiaHelp').onclick=()=>openInternalSite(leiaParanaHelpUrl,'Leia Paraná — Como usar');
$('#syncLeiaParana').onclick=()=>{$('#readingSyncStatus').textContent='Leia Paraná conectado. Entre com sua conta @escola na plataforma oficial para atualizar o progresso.';openInternalSite(leiaParanaUrl,'Leia Paraná — Clube de Leitura');};

const schoolVideoDescriptions={Matemática:'Exercícios e explicações de matemática escolar.',Português:'Gramática, leitura, interpretação e produção de texto.',História:'Aulas de história e contexto social.',Geografia:'Espaço geográfico, mapas, sociedade e meio ambiente.',Ciências:'Conteúdos de ciências para o ensino escolar.',Biologia:'Vida, ecologia, genética e corpo humano.',Física:'Movimento, energia, eletricidade e outros fundamentos.',Química:'Matéria, transformações e fundamentos de química.',Inglês:'Vocabulário, leitura e fundamentos do idioma.',Programação:'Lógica, algoritmos e desenvolvimento de projetos.'};
const khanConnectionStorage='caderno-digital-khan-connected';
function renderKhanConnection(){const connected=localStorage.getItem(khanConnectionStorage)==='true';$('#khanConnectedBadge').classList.toggle('hidden',!connected);$('#finishKhanConnection').classList.add('hidden');$('#disconnectKhan').classList.toggle('hidden',!connected);$('#connectKhan').classList.toggle('hidden',connected);$('#khanConnectTitle').textContent=connected?'Khan Academy vinculada':'Vincule sua Khan Academy';if(connected)$('#khanStatus').textContent='Sua Khan Academy está vinculada neste aparelho.';}
$('#connectKhan').onclick=()=>{const login=window.open('https://pt.khanacademy.org/login','khan-academy-login','popup,width=1100,height=760');if(!login){$('#khanStatus').textContent='O navegador bloqueou a janela. Permita pop-ups ou use um botão de estudo.';return;}$('#finishKhanConnection').classList.remove('hidden');$('#khanStatus').textContent='Entre na Khan Academy e depois clique em “Já entrei — concluir vínculo”.';};
$('#finishKhanConnection').onclick=()=>{localStorage.setItem(khanConnectionStorage,'true');renderKhanConnection();};
$('#disconnectKhan').onclick=()=>{localStorage.removeItem(khanConnectionStorage);$('#khanStatus').textContent='Khan Academy desvinculada deste aparelho.';renderKhanConnection();};
$$('[data-khan-url]').forEach(button=>button.onclick=()=>openInternalSite(button.dataset.khanUrl,button.dataset.khanTitle));renderKhanConnection();
function renderVideoLessons(){const subject=$('#videoSubject').value,source=$('#videoSource').value,query=encodeURIComponent(subject),lessons=[];if(source!=='alura'){const youtubeUrl=subject==='Programação'?`https://www.youtube.com/@CursoemVideo/search?query=${query}`:`https://www.youtube.com/@khanacademyportugues/search?query=${query}`;lessons.push({source:'YOUTUBE EDUCAÇÃO',title:`${subject} — canal educacional`,description:schoolVideoDescriptions[subject],url:youtubeUrl,action:'Ver videoaulas'});}if(source!=='youtube')lessons.push({source:'ALURA',title:`Cursos e aulas de ${subject}`,description:'Conteúdos do catálogo público da Alura relacionados à matéria selecionada.',url:`https://www.alura.com.br/busca?query=${query}`,action:'Ver aulas na Alura'});$('#videoLessonGrid').innerHTML=lessons.map(item=>`<article class="video-lesson-card"><span class="video-source-badge">${escapeHtml(item.source)}</span><h2>${escapeHtml(item.title)}</h2><p>${escapeHtml(item.description)}</p><button class="internal-site-button" data-internal-url="${escapeHtml(item.url)}" data-internal-title="${escapeHtml(item.title)}">${escapeHtml(item.action)}</button></article>`).join('');$$('[data-internal-url]').forEach(button=>button.onclick=()=>openInternalSite(button.dataset.internalUrl,button.dataset.internalTitle));}
$('#videoSubject').onchange=renderVideoLessons;$('#videoSource').onchange=renderVideoLessons;$('#syncVideoLessons').onclick=()=>{renderVideoLessons();$('#videoSyncStatus').textContent='Biblioteca atualizada com a matéria e as fontes educacionais selecionadas.';};renderVideoLessons();

const essayStorage='caderno-digital-essay';
const essayParanaUrl='https://redacao.pr.gov.br/home-student';
let savedEssay={title:'',genre:'Dissertativo-argumentativo',theme:'',text:''};
try{savedEssay={...savedEssay,...JSON.parse(localStorage.getItem(essayStorage)||'{}')};}catch{}
$('#essayTitle').value=savedEssay.title;$('#essayGenre').value=savedEssay.genre;$('#essayTheme').value=savedEssay.theme;$('#essayText').value=savedEssay.text;
function updateEssay(){savedEssay={title:$('#essayTitle').value,genre:$('#essayGenre').value,theme:$('#essayTheme').value,text:$('#essayText').value};const words=savedEssay.text.trim()?savedEssay.text.trim().split(/\s+/).length:0;$('#essayCount').textContent=`${words} palavra${words===1?'':'s'} · ${savedEssay.text.length} caracteres`;$('#essaySaveStatus').textContent='Salvando...';try{localStorage.setItem(essayStorage,JSON.stringify(savedEssay));$('#essaySaveStatus').textContent='Salva automaticamente neste navegador.';}catch{$('#essaySaveStatus').textContent='Não foi possível salvar neste navegador.';}}
['#essayTitle','#essayGenre','#essayTheme','#essayText'].forEach(selector=>$(selector).addEventListener('input',updateEssay));updateEssay();
let internalSiteReturnFocus;
function openInternalSite(url,title='Conteúdo vinculado'){internalSiteReturnFocus=document.activeElement;$('#internalSiteTitle').textContent=title;$('#internalSiteFrame').src=url;$('#internalSiteViewer').classList.remove('hidden');document.body.style.overflow='hidden';$('#closeInternalSite').focus();}
function closeInternalSite(){if($('#internalSiteViewer').classList.contains('hidden'))return;$('#internalSiteViewer').classList.add('hidden');$('#internalSiteFrame').src='about:blank';document.body.style.overflow='';internalSiteReturnFocus?.focus();}
$('#closeInternalSite').onclick=closeInternalSite;$('#internalSiteViewer').addEventListener('click',event=>{if(event.target===$('#internalSiteViewer'))closeInternalSite();});document.addEventListener('keydown',event=>{if(event.key==='Escape')closeInternalSite();});
function openEssayParana(){openInternalSite(essayParanaUrl,'Redação Paraná — Portal do aluno');}
$('#linkEssayParana').onclick=()=>{$('#essaySyncStatus').textContent='A plataforma oficial foi aberta. Entre usando sua conta @Escola.';openEssayParana();};
$('#sendEssayParana').onclick=async()=>{if(!savedEssay.text.trim()){$('#essaySyncStatus').textContent='Escreva sua redação antes de enviar.';$('#essayText').focus();return;}const formatted=`${savedEssay.title.trim()?savedEssay.title.trim()+'\n\n':''}${savedEssay.text.trim()}`;try{await navigator.clipboard.writeText(formatted);$('#essaySyncStatus').textContent='Redação copiada. Na plataforma oficial, entre com @Escola e cole o texto para enviar.';}catch{$('#essaySyncStatus').textContent='Não foi possível copiar automaticamente. Selecione e copie o texto antes de continuar.';}openEssayParana();};

const offlineVideoDbName='caderno-digital-offline-videos';let offlineVideoUrls=[];
function openOfflineVideoDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open(offlineVideoDbName,1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains('videos'))request.result.createObjectStore('videos',{keyPath:'id'});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function offlineVideoTransaction(mode,action){const db=await openOfflineVideoDb();return new Promise((resolve,reject)=>{const transaction=db.transaction('videos',mode),store=transaction.objectStore('videos'),request=action(store);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);transaction.oncomplete=()=>db.close();});}
async function saveOfflineVideo(name,blob){await offlineVideoTransaction('readwrite',store=>store.put({id:crypto.randomUUID(),name,blob,savedAt:Date.now()}));await renderOfflineVideos();}
async function renderOfflineVideos(){offlineVideoUrls.forEach(URL.revokeObjectURL);offlineVideoUrls=[];let videos=[];try{videos=await offlineVideoTransaction('readonly',store=>store.getAll());}catch{$('#offlineVideoGrid').innerHTML='<p class="small-status">O armazenamento offline não está disponível neste navegador.</p>';return;}videos.sort((a,b)=>b.savedAt-a.savedAt);$('#offlineVideoCount').textContent=`${videos.length} vídeo${videos.length===1?'':'s'}`;$('#offlineVideoGrid').innerHTML=videos.length?videos.map(video=>{const url=URL.createObjectURL(video.blob);offlineVideoUrls.push(url);return `<article class="offline-video-card"><video controls preload="metadata" src="${url}" aria-label="Assistir ${escapeHtml(video.name)}"></video><div class="offline-video-info"><strong title="${escapeHtml(video.name)}">${escapeHtml(video.name)}</strong><button data-delete-offline-video="${video.id}" aria-label="Excluir ${escapeHtml(video.name)}">Excluir</button></div></article>`;}).join(''):'<p class="small-status">Nenhum vídeo salvo para assistir offline.</p>';$$('[data-delete-offline-video]').forEach(button=>button.onclick=async()=>{if(!confirm('Deseja excluir este vídeo da biblioteca offline?'))return;await offlineVideoTransaction('readwrite',store=>store.delete(button.dataset.deleteOfflineVideo));renderOfflineVideos();});}
$('#offlineVideoFile').onchange=async event=>{const file=event.target.files[0];if(!file)return;$('#offlineFileStatus').textContent='Salvando vídeo para uso offline...';try{await saveOfflineVideo(file.name,file);$('#offlineFileStatus').textContent='Vídeo salvo. Agora ele pode ser assistido sem internet.';}catch(error){$('#offlineFileStatus').textContent='Não foi possível salvar. Verifique o espaço disponível no navegador.';}event.target.value='';};
$('#downloadVideoUrl').onclick=async()=>{const url=$('#offlineVideoUrl').value.trim(),name=$('#offlineVideoName').value.trim()||'Vídeo offline';if(!url){$('#offlineUrlStatus').textContent='Cole um link direto de vídeo.';return;}$('#offlineUrlStatus').textContent='Baixando o vídeo...';try{const response=await fetch(url);if(!response.ok)throw new Error();const blob=await response.blob();if(!blob.type.startsWith('video/'))throw new Error();await saveOfflineVideo(name,blob);$('#offlineUrlStatus').textContent='Vídeo baixado e salvo para assistir sem internet.';$('#offlineVideoUrl').value='';$('#offlineVideoName').value='';}catch{$('#offlineUrlStatus').textContent='Não foi possível baixar. O link precisa ser direto e permitir download.';}};
renderOfflineVideos();

let recorder, chunks=[], recordTimer, seconds=0, recordings=[], trashedRecordings=[], liveRecognition, liveCaptionText='';
const captionPanel=document.createElement('div');captionPanel.className='live-caption-panel';captionPanel.innerHTML='<label class="accessibility-check"><input id="enableLiveCaptions" type="checkbox"> Ativar legendas ao vivo</label><div id="liveCaptions" class="live-captions" role="log" aria-live="polite"><strong>Legendas:</strong> <span>Aguardando a gravação.</span></div>';
$('#recordStatus').after(captionPanel);
$('#enableLiveCaptions').checked=accessibilityPreferences.deafMode;
function startLiveCaptions(){if(!$('#enableLiveCaptions').checked)return;const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){$('#liveCaptions span').textContent='As legendas ao vivo não estão disponíveis neste navegador. Você ainda pode adicionar um texto à gravação salva.';return;}liveCaptionText='';liveRecognition=new Recognition();liveRecognition.lang='pt-BR';liveRecognition.continuous=true;liveRecognition.interimResults=true;liveRecognition.onresult=event=>{let finalText='',interimText='';for(let i=0;i<event.results.length;i++){const text=event.results[i][0].transcript;if(event.results[i].isFinal)finalText+=text+' ';else interimText+=text;}liveCaptionText=finalText.trim();$('#liveCaptions span').textContent=(finalText+interimText).trim()||'Ouvindo...';};liveRecognition.onerror=()=>{$('#liveCaptions span').textContent='Não foi possível gerar as legendas ao vivo.';};try{liveRecognition.start();$('#liveCaptions span').textContent='Ouvindo...';}catch{}}
function stopLiveCaptions(){if(liveRecognition){try{liveRecognition.stop();}catch{}liveRecognition=null;}if($('#enableLiveCaptions').checked&&!$('#liveCaptions span').textContent.trim())$('#liveCaptions span').textContent='Gravação finalizada.';}
function formatTime(s){return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0');}
function renderRecordings(){const filter=$('#recordFilter').value;const visible=filter==='Todas'?recordings:filter==='personalizada'?recordings.filter(item=>item.custom):recordings.filter(item=>item.subject===filter);$('#recordingsList').innerHTML=visible.length?visible.map(item=>`<div class="audio-item"><span aria-hidden="true">🎙</span><span>${escapeHtml(item.title)}</span><span class="recording-subject">${escapeHtml(item.subject)}</span><audio controls src="${item.url}" aria-label="Ouvir ${escapeHtml(item.title)}"></audio><button class="recording-caption" data-caption="${item.id}" aria-label="Adicionar texto à gravação ${escapeHtml(item.title)}">${item.caption?'Editar texto':'＋ Texto'}</button><button class="delete-recording" data-id="${item.id}" aria-label="Mover ${escapeHtml(item.title)} para a lixeira">🗑</button>${item.caption?`<p class="recording-transcript"><strong>Texto da gravação:</strong> ${escapeHtml(item.caption)}</p>`:''}</div>`).join(''):'<p class="small-status">Nenhuma gravação nesta matéria ainda.</p>';$$('.recording-caption').forEach(button=>button.onclick=()=>{const item=recordings.find(recording=>recording.id===button.dataset.caption),caption=prompt('Digite uma descrição ou transcrição para esta gravação:',item.caption||'');if(caption===null)return;item.caption=caption.trim();renderRecordings();});$$('.delete-recording').forEach(button=>button.onclick=()=>{const index=recordings.findIndex(item=>item.id===button.dataset.id);trashedRecordings.unshift(recordings.splice(index,1)[0]);renderRecordings();renderTrash();});}
function renderTrash(){$('#trashCount').textContent=trashedRecordings.length;$('#trashList').innerHTML=trashedRecordings.length?trashedRecordings.map(item=>`<div class="audio-item"><span>🎙</span><span>${item.title}</span><span class="recording-subject">${item.subject}</span><div class="trash-actions"><button data-restore="${item.id}">Recuperar</button><button class="remove-forever" data-remove="${item.id}">Apagar</button></div></div>`).join(''):'<p class="small-status">A lixeira está vazia.</p>';$$('[data-restore]').forEach(button=>button.onclick=()=>{const index=trashedRecordings.findIndex(item=>item.id===button.dataset.restore);recordings.unshift(trashedRecordings.splice(index,1)[0]);renderRecordings();renderTrash();});$$('[data-remove]').forEach(button=>button.onclick=()=>{const index=trashedRecordings.findIndex(item=>item.id===button.dataset.remove);const [item]=trashedRecordings.splice(index,1);URL.revokeObjectURL(item.url);renderTrash();});}
const deleteSubjectButton=document.createElement('button');deleteSubjectButton.type='button';deleteSubjectButton.className='delete-subject-button hidden';deleteSubjectButton.textContent='Excluir nome da matéria';$('#recordSubjectSelect').after(deleteSubjectButton);
function updateDeleteSubjectButton(){const selected=$('#recordSubjectSelect').selectedOptions[0];deleteSubjectButton.classList.toggle('hidden',!selected?.dataset.customSubject);}
function addCustomRecordingSubject(){const input=$('#customSubject'),subject=input.value.trim();if(!subject)return;[$('#recordSubjectSelect'),$('#recordFilter')].forEach(select=>{if(![...select.options].some(option=>option.value===subject)){const option=document.createElement('option');option.value=subject;option.textContent=subject;option.dataset.customSubject='true';select.insertBefore(option,select.querySelector('option[value="personalizada"]'));}});$('#recordSubjectSelect').value=subject;input.value='';input.classList.add('hidden');updateDeleteSubjectButton();}
$('#recordSubjectSelect').onchange=()=>{$('#customSubject').classList.toggle('hidden',$('#recordSubjectSelect').value!=='personalizada');updateDeleteSubjectButton();};
deleteSubjectButton.onclick=()=>{const subject=$('#recordSubjectSelect').value;if(!$('#recordSubjectSelect').selectedOptions[0]?.dataset.customSubject)return;[$('#recordSubjectSelect'),$('#recordFilter')].forEach(select=>[...select.options].find(option=>option.value===subject)?.remove());$('#recordSubjectSelect').value='Matemática';updateDeleteSubjectButton();};
$('#customSubject').onchange=addCustomRecordingSubject;
$('#customSubject').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();addCustomRecordingSubject();}};
$('#recordFilter').onchange=renderRecordings;
$('#toggleTrash').onclick=()=>{$('#trashPanel').classList.toggle('hidden');renderTrash();};
$('#recordButton').onclick=async()=>{if(recorder?.state==='recording'){stopLiveCaptions();recorder.stop();return;}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>chunks.push(e.data);recorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());clearInterval(recordTimer);$('#recordButton').classList.remove('stop');$('#recordButton').textContent='●';$('#recordVisual').classList.remove('recording');$('#recordTitle').textContent='Gravação salva!';$('#recordStatus').textContent='Você pode ouvir ou gravar outra.';const blob=new Blob(chunks,{type:'audio/webm'}),url=URL.createObjectURL(blob),isCustom=$('#recordSubjectSelect').value==='personalizada',subject=isCustom?$('#customSubject').value.trim()||'Nome da matéria':$('#recordSubjectSelect').value;recordings.unshift({id:crypto.randomUUID(),title:`Gravação ${new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}`,subject,custom:isCustom,url,caption:liveCaptionText});renderRecordings();};recorder.start();startLiveCaptions();seconds=0;$('#recordTime').textContent='00:00';recordTimer=setInterval(()=>$('#recordTime').textContent=formatTime(++seconds),1000);$('#recordButton').classList.add('stop');$('#recordButton').textContent='■';$('#recordVisual').classList.add('recording');$('#recordTitle').textContent='Gravando...';$('#recordStatus').textContent='Toque no quadrado para finalizar.';}catch(err){$('#recordStatus').textContent='Não foi possível usar o microfone. Verifique a permissão do navegador.';}};
renderRecordings();renderTrash();

let subjectPdfs = [];
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char])); }
function renderLibrary() { $('#libraryGrid').innerHTML = subjectPdfs.map(item=>`<article class="pdf-card"><span class="pdf-icon">📄</span><strong title="${escapeHtml(item.name)}">${escapeHtml(item.name)}</strong><small>${escapeHtml(item.subject)}</small><a href="${item.url}" download="${escapeHtml(item.name)}">Baixar PDF</a></article>`).join(''); }
$('#libraryFiles').onchange=e=>{const files=[...e.target.files];if(!files.length)return;const subject=$('#subjectSelect').value;subjectPdfs.push(...files.map(file=>({name:file.name,subject,url:URL.createObjectURL(file)})));renderLibrary();$('#libraryStatus').textContent=`${files.length} PDF(s) adicionado(s) em ${subject}.`;e.target.value='';};
$('#schoolSyncButton').onclick=()=>{const status=$('#schoolStatus');status.textContent='Abrindo o acesso autorizado da sua conta @escola...';connectClassroom();};
const classroomClientStorage = 'caderno-digital-google-client-id';
const classroomEmailStorage = 'caderno-digital-google-gov-email';
if(localStorage.getItem(classroomEmailStorage))$('#classroomSetup').classList.add('hidden');
let classroomTokenClient, classroomAccessToken = '';
const classroomScopes = 'https://www.googleapis.com/auth/classroom.courses.readonly https://www.googleapis.com/auth/classroom.coursework.me.readonly https://www.googleapis.com/auth/classroom.courseworkmaterials.readonly https://www.googleapis.com/auth/drive.readonly';
function loadExternalScript(src) { return new Promise((resolve,reject)=>{const existing=document.querySelector(`script[src="${src}"]`);if(existing){if(existing.dataset.loaded)resolve();else existing.addEventListener('load',resolve,{once:true});return;}const script=document.createElement('script');script.src=src;script.async=true;script.defer=true;script.onload=()=>{script.dataset.loaded='true';resolve();};script.onerror=reject;document.head.append(script);}); }
async function classroomApi(path) { const response=await fetch(`https://classroom.googleapis.com/v1/${path}`,{headers:{Authorization:`Bearer ${classroomAccessToken}`}});if(!response.ok){const detail=await response.json().catch(()=>({}));throw new Error(detail.error?.message||`Erro ${response.status} do Google Classroom`);}return response.json(); }
function classroomPdfAttachments(materials=[], courseName='Classroom') { return materials.flatMap(material=>{const drive=material.driveFile?.driveFile;if(!drive)return[];const title=drive.title||'Material do Classroom';return /\.pdf$/i.test(title)?[{id:drive.id,name:title,subject:courseName}]:[];}); }
async function listClassroomPdfs() { const courses=[];let pageToken='';do{const data=await classroomApi(`courses?courseStates=ACTIVE&pageSize=100${pageToken?`&pageToken=${encodeURIComponent(pageToken)}`:''}`);courses.push(...(data.courses||[]));pageToken=data.nextPageToken||'';}while(pageToken);const found=[];for(const course of courses){for(const endpoint of ['courseWork','courseWorkMaterials']){let token='';do{const data=await classroomApi(`courses/${course.id}/${endpoint}?pageSize=100${token?`&pageToken=${encodeURIComponent(token)}`:''}`);const items=data[endpoint]||[];items.forEach(item=>found.push(...classroomPdfAttachments(item.materials,course.name)));token=data.nextPageToken||'';}while(token);}}return [...new Map(found.map(file=>[file.id,file])).values()]; }
async function downloadClassroomPdf(file) { const response=await fetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(file.id)}?alt=media`,{headers:{Authorization:`Bearer ${classroomAccessToken}`}});if(!response.ok)throw new Error(`Não foi possível baixar ${file.name}`);const blob=await response.blob(),url=URL.createObjectURL(blob);subjectPdfs.unshift({name:file.name,subject:file.subject,url});const link=document.createElement('a');link.href=url;link.download=file.name;document.body.append(link);link.click();link.remove(); }
async function syncClassroomPdfs() { const status=$('#classroomStatus'),schoolStatus=$('#schoolStatus');status.textContent='Procurando PDFs nas suas turmas...';schoolStatus.textContent='Procurando materiais publicados no Google Classroom...';try{const files=await listClassroomPdfs();if(!files.length){status.textContent='Nenhum PDF foi encontrado nas turmas ativas.';schoolStatus.textContent='Acesso concluído, mas nenhum PDF foi encontrado nas turmas ativas.';return;}let downloaded=0;for(const file of files){try{await downloadClassroomPdf(file);downloaded++;status.textContent=`Baixando PDFs... ${downloaded} de ${files.length}`;schoolStatus.textContent=`Recebendo materiais... ${downloaded} de ${files.length}`;}catch{}}renderLibrary();status.textContent=`${downloaded} PDF(s) do Classroom baixado(s) e adicionado(s) à biblioteca.`;schoolStatus.textContent=`✓ ${downloaded} PDF(s) da escola adicionado(s) à biblioteca.`;$('#schoolDescription').textContent='Materiais recebidos das turmas autorizadas no Google Classroom.';$('#schoolSyncButton').textContent='Atualizar PDFs';$('#classroomPageDescription').textContent='✓ Classroom vinculado. O acesso aos PDFs está autorizado.';$('#classroomSyncButton').textContent='Buscar novos PDFs';}catch(error){status.textContent=`Não foi possível sincronizar: ${error.message}`;schoolStatus.textContent=`Não foi possível acessar os PDFs: ${error.message}`;} }
async function connectClassroom() { const email=localStorage.getItem(classroomEmailStorage);if(!email){$('#classroomSetup').classList.remove('hidden');$('#googleGovEmail').focus();return;}const clientId=localStorage.getItem(classroomClientStorage);const status=$('#classroomStatus');if(!clientId){status.textContent='O acesso do Classroom ainda precisa ser liberado pelo responsável do Caderno Digital.';return;}status.textContent='Abrindo a autorização segura do Google...';try{await loadExternalScript('https://accounts.google.com/gsi/client');classroomTokenClient=google.accounts.oauth2.initTokenClient({client_id:clientId,scope:classroomScopes,hint:email,callback:response=>{if(response.error){status.textContent='A autorização do Google não foi concluída.';return;}classroomAccessToken=response.access_token;syncClassroomPdfs();}});classroomTokenClient.requestAccessToken({prompt:classroomAccessToken?'':'consent',hint:email});}catch{status.textContent='Não foi possível carregar a conexão do Google. Verifique sua internet.';} }
$('#classroomSyncButton').onclick=connectClassroom;
$('#openMaterialLibrary').onclick=()=>document.querySelector('[data-tab="exportar"]').click();
$('#saveGoogleGovEmail').onclick=()=>{const input=$('#googleGovEmail'),email=input.value.trim().toLowerCase();if(!input.checkValidity()||!email){$('#classroomStatus').textContent='Digite um e-mail institucional válido.';return;}localStorage.setItem(classroomEmailStorage,email);$('#classroomSetup').classList.add('hidden');connectClassroom();};
const exportButton = $('#exportButton');
if (exportButton) exportButton.onclick=()=>{saveCurrent();window.print();};
$('#pdfFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(!window.pdfjsLib){$('#pdfStatus').textContent='Não foi possível carregar o leitor de PDF. Verifique sua conexão.';return;}$('#pdfStatus').textContent='Lendo o PDF...';try{const data=await file.arrayBuffer(),pdf=await pdfjsLib.getDocument({data}).promise;let text='';for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i),content=await page.getTextContent();text+=content.items.map(x=>x.str).join(' ')+'\n\n';}text=text.replace(/(?:https?:\/\/|www\.)\S+/gi,'').replace(/\b\S+@\S+\.\S+\b/g,'').replace(/\n{3,}/g,'\n\n').trim();$('#transcriptionText').value=text;$('#transcriptionCard').classList.remove('hidden');$('#pdfStatus').textContent=`${pdf.numPages} página(s) transcrita(s), sem links.`;}catch(err){$('#pdfStatus').textContent='Não consegui ler este PDF. Tente outro arquivo.';}};
$('#copyText').onclick=async()=>{try{await navigator.clipboard.writeText($('#transcriptionText').value);$('#copyText').textContent='Texto copiado!';setTimeout(()=>$('#copyText').textContent='Copiar texto',1500);}catch{}};
$('#addTextToNotebook').onclick=()=>{saveCurrent();const pages=activeNotebook().pages;pages.push({title:'Material transcrito',content:'<p class="date">MATERIAL DE ESTUDO</p><h2>Texto transcrito</h2><p>'+$('#transcriptionText').value.replace(/\n/g,'</p><p>')+'</p>',stickers:[]});loadPage(pages.length-1);document.querySelector('[data-tab="caderno"]').click();};
