const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
let paperType = 'lined', currentPage = 0;
let pages = [{ title: 'Página 1', content: $('#paperContent').innerHTML, stickers: [] }];
const stickerData = [
  ['📚','Livros','escola'],['✏️','Lápis','escola'],['🧠','Ideias','escola'],['💻','Computador','escola'],['🖥️','Monitor','escola'],['🔬','Ciência','escola'],['📐','Geometria','escola'],['🎓','Formatura','escola'],
  ['🌈','Arco-íris','diversao'],['🦄','Unicórnio','diversao'],['🎧','Música','diversao'],['⭐','Estrela','diversao'],['🎮','Game','diversao'],['🛼','Patins','diversao'],['🍓','Morango','natureza'],['🌻','Flor','natureza'],['🪴','Planta','natureza'],['🦋','Borboleta','natureza']
];

function saveCurrent() { pages[currentPage].content = $('#paperContent').innerHTML; pages[currentPage].stickers = $$('.placed-sticker').map(el => ({emoji:el.textContent,x:el.style.left,y:el.style.top})); }
function renderPages() { $('#pageList').innerHTML = pages.map((p,i)=>`<button class="${i===currentPage?'active':''}" data-page="${i}">▤ ${p.title}</button>`).join(''); $$('#pageList button').forEach(b=>b.onclick=()=>loadPage(+b.dataset.page)); }
function loadPage(i) { saveCurrent(); currentPage=i; const p=pages[i]; $('#paperContent').innerHTML=p.content; $('#stickerLayer').innerHTML=''; p.stickers.forEach(s=>placeSticker(s.emoji,s.x,s.y)); renderPages(); }
function placeSticker(emoji, x='42%', y='42%') { const el=document.createElement('span'); el.className='placed-sticker'; el.textContent=emoji; el.style.left=x; el.style.top=y; el.setAttribute('aria-label','Adesivo '+emoji); enableDrag(el); $('#stickerLayer').append(el); }
function enableDrag(el) { let sx,sy,ox,oy; el.addEventListener('pointerdown',e=>{e.preventDefault();el.setPointerCapture(e.pointerId);sx=e.clientX;sy=e.clientY;ox=el.offsetLeft;oy=el.offsetTop;el.style.cursor='grabbing';}); el.addEventListener('pointermove',e=>{if(!el.hasPointerCapture(e.pointerId))return;const layer=$('#stickerLayer'), maxX=layer.clientWidth-el.offsetWidth, maxY=layer.clientHeight-el.offsetHeight;el.style.left=Math.max(0,Math.min(maxX,ox+e.clientX-sx))+'px';el.style.top=Math.max(0,Math.min(maxY,oy+e.clientY-sy))+'px';}); el.addEventListener('pointerup',e=>{el.releasePointerCapture(e.pointerId);el.style.cursor='grab';saveCurrent();}); el.addEventListener('dblclick',()=>{el.remove();saveCurrent();}); }

$$('.nav-item').forEach(button=>button.addEventListener('click',()=>{saveCurrent(); $$('.nav-item').forEach(b=>b.classList.toggle('active',b===button)); $$('.tab-panel').forEach(p=>p.classList.toggle('active',p.id===button.dataset.tab)); $('.sidebar').classList.remove('open'); window.scrollTo({top:0,behavior:'smooth'}); }));
$('#menuButton').onclick=()=>$('.sidebar').classList.toggle('open');
$$('.cover-choice').forEach(b=>b.onclick=()=>{ $$('.cover-choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('#notebook').className='notebook '+b.dataset.cover+'-cover'; });
$$('.paper-option').forEach(b=>b.onclick=()=>{paperType=b.dataset.paper;$$('.paper-option').forEach(x=>x.classList.toggle('selected',x===b));$('#paper').className='paper '+paperType+'-paper';});
$('#newPage').onclick=()=>{saveCurrent();pages.push({title:'Página '+(pages.length+1),content:'<p class="date">NOVA PÁGINA</p><h2>Minha nova ideia ✦</h2><p>Comece a escrever aqui...</p>',stickers:[]});loadPage(pages.length-1);}; renderPages();

function renderStickers(category='todos'){const list=category==='todos'?stickerData:stickerData.filter(s=>s[2]===category);$('#stickerGallery').innerHTML=list.map(([emoji,name])=>`<button class="sticker-card" data-emoji="${emoji}"><span class="emoji">${emoji}</span><small>${name}</small></button>`).join('');$$('.sticker-card').forEach(b=>b.onclick=()=>{placeSticker(b.dataset.emoji);saveCurrent();});}renderStickers();
$$('.sticker-filter').forEach(b=>b.onclick=()=>{$$('.sticker-filter').forEach(x=>x.classList.toggle('active',x===b));renderStickers(b.dataset.category);});

const answers = {fotossíntese:'A fotossíntese é como a cozinha das plantas: usando luz do sol, água e gás carbônico, ela produz açúcar para ter energia e libera oxigênio. Acontece principalmente nas folhas, graças à clorofila.',equação:'Para resolver uma equação de 1º grau, deixe o x sozinho em um lado do sinal de igual. Exemplo: 2x + 4 = 10. Tire 4 dos dois lados: 2x = 6. Depois divida ambos por 2: x = 3.',resumo:'Para criar um bom resumo: 1) leia o assunto, 2) anote só as ideias principais com suas palavras, 3) use títulos e exemplos, e 4) releia tentando explicar sem olhar. Posso ajudar se você colar o texto aqui.',alura:'Nas aulas da Alura, pause quando surgir um conceito novo, anote a ideia principal e teste o que foi mostrado. Se você me disser o tema ou colar um trecho da aula, eu explico passo a passo com exemplos.'};
function reply(question){const q=question.toLowerCase();if(q.includes('fotossíntese'))return answers.fotossíntese;if(q.includes('equação')||q.includes('primeiro grau'))return answers.equação;if(q.includes('resumo'))return answers.resumo;if(q.includes('alura'))return answers.alura;return 'Ótima pergunta! Para estudar esse assunto, comece identificando os conceitos principais e procurando um exemplo prático. Conte qual parte está mais difícil ou cole um trecho do material que eu explico de um jeito mais simples.';}
function addMessage(text,type){const m=document.createElement('div');m.className='message '+type;m.textContent=text;$('#chatBox').append(m);$('#chatBox').scrollTop=$('#chatBox').scrollHeight;}
$('#aiForm').onsubmit=e=>{e.preventDefault();const input=$('#aiQuestion'),q=input.value.trim();if(!q)return;addMessage(q,'user');input.value='';setTimeout(()=>addMessage(reply(q),'luma'),250);};$$('.suggestions button').forEach(b=>b.onclick=()=>{$('#aiQuestion').value=b.dataset.question;$('#aiForm').requestSubmit();});

let recorder, chunks=[], recordTimer, seconds=0; function formatTime(s){return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0');}
$('#recordButton').onclick=async()=>{if(recorder?.state==='recording'){recorder.stop();return;}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>chunks.push(e.data);recorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());clearInterval(recordTimer);$('#recordButton').classList.remove('stop');$('#recordButton').textContent='●';$('#recordVisual').classList.remove('recording');$('#recordTitle').textContent='Gravação salva!';$('#recordStatus').textContent='Você pode ouvir ou gravar outra.';const blob=new Blob(chunks,{type:'audio/webm'}),url=URL.createObjectURL(blob),item=document.createElement('div');item.className='audio-item';item.innerHTML=`<span>🎙</span><span>Gravação ${new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</span>`;const audio=document.createElement('audio');audio.controls=true;audio.src=url;item.append(audio);$('#recordingsList').prepend(item);};recorder.start();seconds=0;$('#recordTime').textContent='00:00';recordTimer=setInterval(()=>$('#recordTime').textContent=formatTime(++seconds),1000);$('#recordButton').classList.add('stop');$('#recordButton').textContent='■';$('#recordVisual').classList.add('recording');$('#recordTitle').textContent='Gravando...';$('#recordStatus').textContent='Toque no quadrado para finalizar.';}catch(err){$('#recordStatus').textContent='Não foi possível usar o microfone. Verifique a permissão do navegador.';}};

$('#exportButton').onclick=()=>{saveCurrent();window.print();};
$('#pdfFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(!window.pdfjsLib){$('#pdfStatus').textContent='Não foi possível carregar o leitor de PDF. Verifique sua conexão.';return;}$('#pdfStatus').textContent='Lendo o PDF...';try{const data=await file.arrayBuffer(),pdf=await pdfjsLib.getDocument({data}).promise;let text='';for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i),content=await page.getTextContent();text+=content.items.map(x=>x.str).join(' ')+'\n\n';}text=text.replace(/(?:https?:\/\/|www\.)\S+/gi,'').replace(/\b\S+@\S+\.\S+\b/g,'').replace(/\n{3,}/g,'\n\n').trim();$('#transcriptionText').value=text;$('#transcriptionCard').classList.remove('hidden');$('#pdfStatus').textContent=`${pdf.numPages} página(s) transcrita(s), sem links.`;}catch(err){$('#pdfStatus').textContent='Não consegui ler este PDF. Tente outro arquivo.';}};
$('#copyText').onclick=async()=>{try{await navigator.clipboard.writeText($('#transcriptionText').value);$('#copyText').textContent='Texto copiado!';setTimeout(()=>$('#copyText').textContent='Copiar texto',1500);}catch{}};
$('#addTextToNotebook').onclick=()=>{saveCurrent();pages.push({title:'Material transcrito',content:'<p class="date">MATERIAL DE ESTUDO</p><h2>Texto transcrito</h2><p>'+$('#transcriptionText').value.replace(/\n/g,'</p><p>')+'</p>',stickers:[]});loadPage(pages.length-1);document.querySelector('[data-tab="caderno"]').click();};
