const assert = require('node:assert/strict');
const {classify,current,minutes}=require('./lesson-status.js');
const date='2026-09-25';
assert.equal(classify({lessonEvidence:'https://meet.google.com/abc-defg-hij'},date).type,'meet');
assert.equal(classify({lessonEvidence:'Aula assíncrona gravada'},date).type,'recording');
assert.equal(classify({lessonEvidence:'Gravação do Meet'},date).type,'unknown');
assert.equal(classify({lessonEvidence:'Não teremos Meet'},date).type,'unknown');
assert.equal(classify({lessonEvidence:'https://youtube.com/watch?v=abc'},date).type,'unknown');
assert.equal(classify({lessonType:'recording',dayOverride:{date,type:'free'}},date).type,'free');
assert.equal(classify({lessonType:'recording',dayOverride:{date,type:'free'}},'2026-09-26').type,'recording');
const lesson={day:5,time:'08:00',endTime:'09:00'};
assert.equal(current([lesson],new Date(2026,8,25,8,0)).lesson,lesson);
assert.match(current([lesson],new Date(2026,8,25,9,0)).message,/Fora/);
assert.match(current([lesson,{day:5,time:'2ª aula'}],new Date(2026,8,25,8,30)).message,/preencha/);
assert.match(current([lesson,lesson],new Date(2026,8,25,8,30)).message,/sobrepostos/);
assert.match(current([lesson,{day:5,time:'10:00',endTime:'11:00'}],new Date(2026,8,25,9,30)).message,/Intervalo/);
assert.match(current([],new Date(2026,8,26)).message,/Nenhuma aula/);
assert.equal(minutes('24:00'),null);
assert.equal(minutes('1ª aula'),null);
console.log('15 verificações passaram.');

const {lessonChanges}=require('./lesson-status.js');
const original={id:'a',day:1,time:'1ª aula',subjectId:'math'};
const saved=lessonChanges(original,{start:'',end:'',type:'meet',evidence:' aviso ',override:null});
assert.equal(saved.id,'a');assert.equal(saved.time,'1ª aula');assert.equal(saved.lessonType,'meet');assert.equal(saved.lessonEvidence,'aviso');assert.equal(original.lessonType,undefined);
assert.throws(()=>lessonChanges(original,{start:'08:00',end:'',type:'meet',evidence:''}));
const timed=lessonChanges(saved,{start:'08:00',end:'09:00',type:'recording',evidence:'',override:null});
assert.equal(timed.time,'08:00');assert.equal(timed.endTime,'09:00');assert.equal(JSON.parse(JSON.stringify(timed)).lessonType,'recording');
console.log('Salvamento por aula e preservação dos horários verificados.');
